==>> Time: 29-01-2024 15:15:01
==>> Type: <class 'sqlite3.OperationalError'>
==>> Value: near ",": syntax error
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\AddUserWindow.py", line 42, in startAddingToDB
    cursor.execute(sql_query, (profileName, uore,

==>> Time: 29-01-2024 15:15:38
==>> Type: <class 'sqlite3.OperationalError'>
==>> Value: near ",": syntax error
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\AddUserWindow.py", line 42, in startAddingToDB
    cursor.execute(sql_query, (profileName, uore,

==>> Time: 29-01-2024 15:53:25
==>> Type: <class 'TypeError'>
==>> Value: setUpProfilesTable.<locals>.<lambda>() missing 1 required positional argument: 'table'
==>> Traceback:

==>> Time: 29-01-2024 15:53:39
==>> Type: <class 'TypeError'>
==>> Value: setUpProfilesTable.<locals>.<lambda>() missing 1 required positional argument: 'table'
==>> Traceback:

==>> Time: 29-01-2024 15:55:08
==>> Type: <class 'TypeError'>
==>> Value: customMenu() missing 1 required positional argument: 'table'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 12, in <lambda>
    table.contextMenuEvent = lambda table: customMenu(table)
                                           ^^^^^^^^^^^^^^^^^

==>> Time: 29-01-2024 15:55:37
==>> Type: <class 'TypeError'>
==>> Value: setUpProfilesTable.<locals>.<lambda>() missing 1 required positional argument: 'table'
==>> Traceback:

==>> Time: 29-01-2024 17:10:34
==>> Type: <class 'KeyError'>
==>> Value: '104.129.48.19:4444:tiktok2024:bonbon9999'
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\AddUserWindow.py", line 58, in startAddingToDB
    self.loadProfilesToTableFunc()
  File "d:\Folinas Socials Tool\windows\HomeWindow.py", line 55, in loadProfilesToTable
    row, 4, QTableWidgetItemCenter(data[record[7]]))
                                   ~~~~^^^^^^^^^^^

==>> Time: 30-01-2024 09:18:05
==>> Type: <class 'TypeError'>
==>> Value: FacebookLogin.stateAccount[int, str] signal has 2 argument(s) but 1 provided
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 34, in run
    self.stateAccount.emit('Khởi tạo trình duyệt')

==>> Time: 30-01-2024 09:18:52
==>> Type: <class 'IndexError'>
==>> Value: tuple index out of range
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 35, in run
    driver = startBrowserFromUore(
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 99, in startBrowserFromUore
    proxy = record[15]
            ~~~~~~^^^^

==>> Time: 30-01-2024 09:19:39
==>> Type: <class 'FileNotFoundError'>
==>> Value: [Errno 2] No such file or directory: './last_location/last_location.json'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 35, in run
    driver = startBrowserFromUore(
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 103, in startBrowserFromUore
    with open('./last_location/last_location.json', 'r+', encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

==>> Time: 30-01-2024 09:20:31
==>> Type: <class 'FileNotFoundError'>
==>> Value: [Errno 2] No such file or directory: './last_location/last_location.json'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 35, in run
    driver = startBrowserFromUore(
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 103, in startBrowserFromUore
    with open('./last_location/last_location.json', 'r+', encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

==>> Time: 30-01-2024 09:21:07
==>> Type: <class 'IndexError'>
==>> Value: tuple index out of range
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 35, in run
    driver = startBrowserFromUore(
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 107, in startBrowserFromUore
    id_browser = record[18]
                 ~~~~~~^^^^

==>> Time: 30-01-2024 09:21:21
==>> Type: <class 'IndexError'>
==>> Value: tuple index out of range
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 35, in run
    driver = startBrowserFromUore(
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 113, in startBrowserFromUore
    ACTION_FOR_BROWSER_CREATE, proxy, user_agent, webgl_vendor, longla, record[17])
                                                                        ~~~~~~^^^^

==>> Time: 30-01-2024 09:31:13
==>> Type: <class 'TypeError'>
==>> Value: super(type, obj): obj must be an instance or subtype of type
==>> Traceback:
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 44, in <lambda>
    table.contextMenuEvent = lambda event: customMenu(event, table)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 39, in customMenu
    editThisAccountWindow(index.row(), table)
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 18, in editThisAccountWindow
    table.editUserWindow = EditUserWindow(uore)
                           ^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\windows\AddUserWindow.py", line 75, in __init__
    super(AddUserWindow, self).__init__()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^

==>> Time: 30-01-2024 09:34:02
==>> Type: <class 'TypeError'>
==>> Value: setChecked(self, a0: bool): not enough arguments
==>> Traceback:
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 45, in <lambda>
    table.contextMenuEvent = lambda event: customMenu(event, table)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 40, in customMenu
    editThisAccountWindow(index.row(), table)
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 18, in editThisAccountWindow
    table.editUserWindow = EditUserWindow(uore)
                           ^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\windows\AddUserWindow.py", line 94, in __init__
    self.ui.http.setChecked()

==>> Time: 30-01-2024 09:47:57
==>> Type: <class 'TypeError'>
==>> Value: FacebookLogin.loginNormal() takes 2 positional arguments but 3 were given
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 57, in run
    self.loginNormal(self, browser)

==>> Time: 30-01-2024 14:36:25
==>> Type: <class 'AttributeError'>
==>> Value: 'NoneType' object has no attribute 'send_keys'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 59, in run
    self.loginNormal(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 88, in loginNormal
    inputEmail.send_keys(self.username)
    ^^^^^^^^^^^^^^^^^^^^

==>> Time: 30-01-2024 15:30:12
==>> Type: <class 'sqlite3.OperationalError'>
==>> Value: no such table: profiles
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 60, in run
    self.loginNormal(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 96, in loginNormal
    cursor.execute(sql_query, (1, self.username))

==>> Time: 30-01-2024 15:32:41
==>> Type: <class 'AttributeError'>
==>> Value: 'NoneType' object has no attribute 'click'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 60, in run
    self.loginNormal(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 126, in loginNormal
    continueBtn.click()
    ^^^^^^^^^^^^^^^^^

==>> Time: 30-01-2024 17:25:10
==>> Type: <class 'AttributeError'>
==>> Value: 'NoneType' object has no attribute 'send_keys'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 60, in run
    self.loginNormal(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 108, in loginNormal
    inputEmail.send_keys(self.username)
    ^^^^^^^^^^^^^^^^^^^^

==>> Time: 31-01-2024 09:47:34
==>> Type: <class 'UnboundLocalError'>
==>> Value: cannot access local variable 'getAssets' where it is not associated with a value
==>> Traceback:
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 96, in <lambda>
    table.contextMenuEvent = lambda event: customMenu(event, table)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 90, in customMenu
    elif res == getAssets:
                ^^^^^^^^^

==>> Time: 31-01-2024 09:48:02
==>> Type: <class 'UnboundLocalError'>
==>> Value: cannot access local variable 'getAssets' where it is not associated with a value
==>> Traceback:
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 96, in <lambda>
    table.contextMenuEvent = lambda event: customMenu(event, table)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 90, in customMenu
    elif getAssets and res == getAssets:
         ^^^^^^^^^

==>> Time: 31-01-2024 09:57:18
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: unknown error: cannot connect to chrome at 127.0.0.1:14308
from session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 114.0.5735.45
Stacktrace:
Backtrace:
	Ordinal0 [0x008B2733+2434867]
	Ordinal0 [0x008407A1+1968033]
	Ordinal0 [0x0072C678+837240]
	Ordinal0 [0x0074CAC3+969411]
	Ordinal0 [0x007460DB+942299]
	Ordinal0 [0x00745EA6+941734]
	Ordinal0 [0x007790B0+1151152]
	Ordinal0 [0x00778D0A+1150218]
	Ordinal0 [0x00774256+1131094]
	Ordinal0 [0x0074E840+976960]
	Ordinal0 [0x0074F736+980790]
	GetHandleVerifier [0x00B23C72+2515426]
	GetHandleVerifier [0x00B1702F+2463135]
	GetHandleVerifier [0x0095522A+620442]
	GetHandleVerifier [0x00954016+615814]
	Ordinal0 [0x0084707B+1994875]
	Ordinal0 [0x0084B938+2013496]
	Ordinal0 [0x0084BA25+2013733]
	Ordinal0 [0x00854DE1+2051553]
	BaseThreadInitThunk [0x76C6FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77747C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77747C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 166, in run
    driver = startBrowserFromUore(
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 313, in startBrowserFromUore
    driver = openBrowser(ACTION_FOR_BROWSER_OPEN, int(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\ControlBrowser.py", line 270, in openBrowser
    driver = Chrome(service=Service(web_driver_path), options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 31-01-2024 09:57:55
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: disconnected: unable to send message to renderer
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=114.0.5735.45)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00546E73+48323]
	(No symbol) [0x004D9661]
	(No symbol) [0x003E5308]
	(No symbol) [0x003D70D0]
	(No symbol) [0x003D775A]
	(No symbol) [0x003E7221]
	(No symbol) [0x003E77CF]
	(No symbol) [0x003E9991]
	(No symbol) [0x003E9A30]
	(No symbol) [0x0043E6E8]
	(No symbol) [0x0043E465]
	(No symbol) [0x0042A8DC]
	(No symbol) [0x0043CAC2]
	(No symbol) [0x0042A6D6]
	(No symbol) [0x0040847C]
	(No symbol) [0x0040957D]
	GetHandleVerifier [0x007AFD5D+2575277]
	GetHandleVerifier [0x007EF86E+2836158]
	GetHandleVerifier [0x007E96DC+2811180]
	GetHandleVerifier [0x005D41B0+626688]
	(No symbol) [0x004E314C]
	(No symbol) [0x004DF4B8]
	(No symbol) [0x004DF59B]
	(No symbol) [0x004D21B7]
	BaseThreadInitThunk [0x76C6FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77747C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77747C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 182, in run
    self.loginNormal(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 212, in loginNormal
    browser.get('https://www.youtube.com/')
  File "d:\Folinas Socials Tool\core\SeleniumFunctions.py", line 29, in get
    clean_current = self.driver.current_url.split('://')[-1]
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 437, in current_url
    return self.execute(Command.GET_CURRENT_URL)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 31-01-2024 10:00:48
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: disconnected: unable to send message to renderer
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=114.0.5735.45)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00546E73+48323]
	(No symbol) [0x004D9661]
	(No symbol) [0x003E5308]
	(No symbol) [0x003D70D0]
	(No symbol) [0x003D775A]
	(No symbol) [0x003E7221]
	(No symbol) [0x003E77CF]
	(No symbol) [0x003E9991]
	(No symbol) [0x003E9A30]
	(No symbol) [0x0043E6E8]
	(No symbol) [0x0043E465]
	(No symbol) [0x0042A8DC]
	(No symbol) [0x0043CAC2]
	(No symbol) [0x0042A6D6]
	(No symbol) [0x0040847C]
	(No symbol) [0x0040957D]
	GetHandleVerifier [0x007AFD5D+2575277]
	GetHandleVerifier [0x007EF86E+2836158]
	GetHandleVerifier [0x007E96DC+2811180]
	GetHandleVerifier [0x005D41B0+626688]
	(No symbol) [0x004E314C]
	(No symbol) [0x004DF4B8]
	(No symbol) [0x004DF59B]
	(No symbol) [0x004D21B7]
	BaseThreadInitThunk [0x76C6FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77747C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77747C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 182, in run
    self.loginNormal(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 212, in loginNormal
    browser.get('https://www.youtube.com/')
  File "d:\Folinas Socials Tool\core\SeleniumFunctions.py", line 29, in get
    clean_current = self.driver.current_url.split('://')[-1]
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 437, in current_url
    return self.execute(Command.GET_CURRENT_URL)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 31-01-2024 10:06:27
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: disconnected: unable to send message to renderer
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=114.0.5735.45)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00546E73+48323]
	(No symbol) [0x004D9661]
	(No symbol) [0x003E5308]
	(No symbol) [0x003D70D0]
	(No symbol) [0x003D775A]
	(No symbol) [0x003E7221]
	(No symbol) [0x003E77CF]
	(No symbol) [0x003E9991]
	(No symbol) [0x003E9A30]
	(No symbol) [0x0043E6E8]
	(No symbol) [0x0043E465]
	(No symbol) [0x0042A8DC]
	(No symbol) [0x0043CAC2]
	(No symbol) [0x0042A6D6]
	(No symbol) [0x0040847C]
	(No symbol) [0x0040957D]
	GetHandleVerifier [0x007AFD5D+2575277]
	GetHandleVerifier [0x007EF86E+2836158]
	GetHandleVerifier [0x007E96DC+2811180]
	GetHandleVerifier [0x005D41B0+626688]
	(No symbol) [0x004E314C]
	(No symbol) [0x004DF4B8]
	(No symbol) [0x004DF59B]
	(No symbol) [0x004D21B7]
	BaseThreadInitThunk [0x76C6FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77747C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77747C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 183, in run
    self.loginNormal(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 224, in loginNormal
    browser.get('https://www.youtube.com/')
  File "d:\Folinas Socials Tool\core\SeleniumFunctions.py", line 29, in get
    clean_current = self.driver.current_url.split('://')[-1]
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 437, in current_url
    return self.execute(Command.GET_CURRENT_URL)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 31-01-2024 10:11:15
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: disconnected: unable to send message to renderer
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=114.0.5735.45)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00546E73+48323]
	(No symbol) [0x004D9661]
	(No symbol) [0x003E5308]
	(No symbol) [0x003D70D0]
	(No symbol) [0x003D775A]
	(No symbol) [0x003E7221]
	(No symbol) [0x003E77CF]
	(No symbol) [0x003E9991]
	(No symbol) [0x003E9A30]
	(No symbol) [0x0043E6E8]
	(No symbol) [0x0043E465]
	(No symbol) [0x0042A8DC]
	(No symbol) [0x0043CAC2]
	(No symbol) [0x0042A6D6]
	(No symbol) [0x0040847C]
	(No symbol) [0x0040957D]
	GetHandleVerifier [0x007AFD5D+2575277]
	GetHandleVerifier [0x007EF86E+2836158]
	GetHandleVerifier [0x007E96DC+2811180]
	GetHandleVerifier [0x005D41B0+626688]
	(No symbol) [0x004E314C]
	(No symbol) [0x004DF4B8]
	(No symbol) [0x004DF59B]
	(No symbol) [0x004D21B7]
	BaseThreadInitThunk [0x76C6FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77747C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77747C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 183, in run
    self.loginNormal(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 225, in loginNormal
    browser.get('https://www.youtube.com/')
  File "d:\Folinas Socials Tool\core\SeleniumFunctions.py", line 29, in get
    clean_current = self.driver.current_url.split('://')[-1]
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 437, in current_url
    return self.execute(Command.GET_CURRENT_URL)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 31-01-2024 10:15:55
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: disconnected: unable to send message to renderer
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=114.0.5735.45)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00546E73+48323]
	(No symbol) [0x004D9661]
	(No symbol) [0x003E5308]
	(No symbol) [0x003D70D0]
	(No symbol) [0x003D775A]
	(No symbol) [0x003E7221]
	(No symbol) [0x003E77CF]
	(No symbol) [0x003E9991]
	(No symbol) [0x003E9A30]
	(No symbol) [0x0043E6E8]
	(No symbol) [0x0043E465]
	(No symbol) [0x0042A8DC]
	(No symbol) [0x0043CAC2]
	(No symbol) [0x0042A6D6]
	(No symbol) [0x0040847C]
	(No symbol) [0x0040957D]
	GetHandleVerifier [0x007AFD5D+2575277]
	GetHandleVerifier [0x007EF86E+2836158]
	GetHandleVerifier [0x007E96DC+2811180]
	GetHandleVerifier [0x005D41B0+626688]
	(No symbol) [0x004E314C]
	(No symbol) [0x004DF4B8]
	(No symbol) [0x004DF59B]
	(No symbol) [0x004D21B7]
	BaseThreadInitThunk [0x76C6FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77747C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77747C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 183, in run
    self.loginNormal(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 225, in loginNormal
    browser.get('https://www.youtube.com/')
  File "d:\Folinas Socials Tool\core\SeleniumFunctions.py", line 29, in get
    clean_current = self.driver.current_url.split('://')[-1]
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 437, in current_url
    return self.execute(Command.GET_CURRENT_URL)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 31-01-2024 10:22:42
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: disconnected: unable to send message to renderer
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=114.0.5735.45)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00546E73+48323]
	(No symbol) [0x004D9661]
	(No symbol) [0x003E5308]
	(No symbol) [0x003D70D0]
	(No symbol) [0x003D775A]
	(No symbol) [0x003E7221]
	(No symbol) [0x003E77CF]
	(No symbol) [0x003E9991]
	(No symbol) [0x003E9A30]
	(No symbol) [0x0043E6E8]
	(No symbol) [0x0043E465]
	(No symbol) [0x0042A8DC]
	(No symbol) [0x0043CAC2]
	(No symbol) [0x0042A6D6]
	(No symbol) [0x0040847C]
	(No symbol) [0x0040957D]
	GetHandleVerifier [0x007AFD5D+2575277]
	GetHandleVerifier [0x007EF86E+2836158]
	GetHandleVerifier [0x007E96DC+2811180]
	GetHandleVerifier [0x005D41B0+626688]
	(No symbol) [0x004E314C]
	(No symbol) [0x004DF4B8]
	(No symbol) [0x004DF59B]
	(No symbol) [0x004D21B7]
	BaseThreadInitThunk [0x76C6FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77747C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77747C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 183, in run
    self.loginNormal(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 225, in loginNormal
    browser.get('https://www.youtube.com/')
  File "d:\Folinas Socials Tool\core\SeleniumFunctions.py", line 29, in get
    clean_current = self.driver.current_url.split('://')[-1]
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 437, in current_url
    return self.execute(Command.GET_CURRENT_URL)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 31-01-2024 10:24:46
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: unknown error: cannot connect to chrome at 127.0.0.1:12588
from session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 114.0.5735.45
Stacktrace:
Backtrace:
	Ordinal0 [0x008B2733+2434867]
	Ordinal0 [0x008407A1+1968033]
	Ordinal0 [0x0072C678+837240]
	Ordinal0 [0x0074CAC3+969411]
	Ordinal0 [0x007460DB+942299]
	Ordinal0 [0x00745EA6+941734]
	Ordinal0 [0x007790B0+1151152]
	Ordinal0 [0x00778D0A+1150218]
	Ordinal0 [0x00774256+1131094]
	Ordinal0 [0x0074E840+976960]
	Ordinal0 [0x0074F736+980790]
	GetHandleVerifier [0x00B23C72+2515426]
	GetHandleVerifier [0x00B1702F+2463135]
	GetHandleVerifier [0x0095522A+620442]
	GetHandleVerifier [0x00954016+615814]
	Ordinal0 [0x0084707B+1994875]
	Ordinal0 [0x0084B938+2013496]
	Ordinal0 [0x0084BA25+2013733]
	Ordinal0 [0x00854DE1+2051553]
	BaseThreadInitThunk [0x76C6FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77747C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77747C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 167, in run
    driver = startBrowserFromUore(
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 326, in startBrowserFromUore
    driver = openBrowser(ACTION_FOR_BROWSER_OPEN, int(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\ControlBrowser.py", line 270, in openBrowser
    driver = Chrome(service=Service(web_driver_path), options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 31-01-2024 14:10:44
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: unknown error: cannot connect to chrome at 127.0.0.1:13305
from session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 114.0.5735.45
Stacktrace:
Backtrace:
	Ordinal0 [0x008B2733+2434867]
	Ordinal0 [0x008407A1+1968033]
	Ordinal0 [0x0072C678+837240]
	Ordinal0 [0x0074CAC3+969411]
	Ordinal0 [0x007460DB+942299]
	Ordinal0 [0x00745EA6+941734]
	Ordinal0 [0x007790B0+1151152]
	Ordinal0 [0x00778D0A+1150218]
	Ordinal0 [0x00774256+1131094]
	Ordinal0 [0x0074E840+976960]
	Ordinal0 [0x0074F736+980790]
	GetHandleVerifier [0x00B23C72+2515426]
	GetHandleVerifier [0x00B1702F+2463135]
	GetHandleVerifier [0x0095522A+620442]
	GetHandleVerifier [0x00954016+615814]
	Ordinal0 [0x0084707B+1994875]
	Ordinal0 [0x0084B938+2013496]
	Ordinal0 [0x0084BA25+2013733]
	Ordinal0 [0x00854DE1+2051553]
	BaseThreadInitThunk [0x76C6FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77747C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77747C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 209, in run
    driver = startBrowserFromUore(
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 278, in startBrowserFromUore
    driver = openBrowser(ACTION_FOR_BROWSER_OPEN, int(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\ControlBrowser.py", line 270, in openBrowser
    driver = Chrome(service=Service(web_driver_path), options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 31-01-2024 16:13:09
==>> Type: <class 'AttributeError'>
==>> Value: 'NoneType' object has no attribute 'send_keys'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 295, in run
    inputBtn.send_keys(self.username)
    ^^^^^^^^^^^^^^^^^^

==>> Time: 31-01-2024 16:19:02
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: unknown error: cannot connect to chrome at 127.0.0.1:7624
from session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 114.0.5735.45
Stacktrace:
Backtrace:
	Ordinal0 [0x00AE2733+2434867]
	Ordinal0 [0x00A707A1+1968033]
	Ordinal0 [0x0095C678+837240]
	Ordinal0 [0x0097CAC3+969411]
	Ordinal0 [0x009760DB+942299]
	Ordinal0 [0x00975EA6+941734]
	Ordinal0 [0x009A90B0+1151152]
	Ordinal0 [0x009A8D0A+1150218]
	Ordinal0 [0x009A4256+1131094]
	Ordinal0 [0x0097E840+976960]
	Ordinal0 [0x0097F736+980790]
	GetHandleVerifier [0x00D53C72+2515426]
	GetHandleVerifier [0x00D4702F+2463135]
	GetHandleVerifier [0x00B8522A+620442]
	GetHandleVerifier [0x00B84016+615814]
	Ordinal0 [0x00A7707B+1994875]
	Ordinal0 [0x00A7B938+2013496]
	Ordinal0 [0x00A7BA25+2013733]
	Ordinal0 [0x00A84DE1+2051553]
	BaseThreadInitThunk [0x76C6FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77747C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77747C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 286, in run
    driver = startBrowserFromUore(
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 351, in startBrowserFromUore
    driver = openBrowser(ACTION_FOR_BROWSER_OPEN, int(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\ControlBrowser.py", line 270, in openBrowser
    driver = Chrome(service=Service(web_driver_path), options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 01-02-2024 08:09:49
==>> Type: <class 'TypeError'>
==>> Value: invalid result from getAssetsFacebookThread.run()
==>> Traceback:

==>> Time: 01-02-2024 08:14:54
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: unknown error: cannot connect to chrome at 127.0.0.1:10663
from session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 114.0.5735.45
Stacktrace:
Backtrace:
	Ordinal0 [0x00962733+2434867]
	Ordinal0 [0x008F07A1+1968033]
	Ordinal0 [0x007DC678+837240]
	Ordinal0 [0x007FCAC3+969411]
	Ordinal0 [0x007F60DB+942299]
	Ordinal0 [0x007F5EA6+941734]
	Ordinal0 [0x008290B0+1151152]
	Ordinal0 [0x00828D0A+1150218]
	Ordinal0 [0x00824256+1131094]
	Ordinal0 [0x007FE840+976960]
	Ordinal0 [0x007FF736+980790]
	GetHandleVerifier [0x00BD3C72+2515426]
	GetHandleVerifier [0x00BC702F+2463135]
	GetHandleVerifier [0x00A0522A+620442]
	GetHandleVerifier [0x00A04016+615814]
	Ordinal0 [0x008F707B+1994875]
	Ordinal0 [0x008FB938+2013496]
	Ordinal0 [0x008FBA25+2013733]
	Ordinal0 [0x00904DE1+2051553]
	BaseThreadInitThunk [0x7635FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x775A7C6E+286]
	RtlGetAppContainerNamedObjectPath [0x775A7C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 127, in run
    driver = startBrowserFromUore(
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 459, in startBrowserFromUore
    driver = openBrowser(ACTION_FOR_BROWSER_OPEN, int(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\ControlBrowser.py", line 270, in openBrowser
    driver = Chrome(service=Service(web_driver_path), options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 01-02-2024 12:44:51
==>> Type: <class 'AttributeError'>
==>> Value: 'HomeWindow' object has no attribute 'loadFromFolderThread'
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\HomeWindow.py", line 76, in loadFilesFromFolder
    if self.loadFromFolderThread != None and self.loadFromFolderThread.isRunning():
       ^^^^^^^^^^^^^^^^^^^^^^^^^

==>> Time: 01-02-2024 14:26:06
==>> Type: <class 'TypeError'>
==>> Value: setText(self, a0: Optional[str]): argument 1 has unexpected type 'QTableWidgetItemCenter'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 264, in <lambda>
    table.contextMenuEvent = lambda event: customMenuVideos(
                                           ^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 250, in customMenuVideos
    editThisVideo(index.row(), table)
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 220, in editThisVideo
    table.editWindow = ReadUpdateVideoWindow()
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 216, in __init__
    self.ui.titleLine.setText(table.item(index, 0))

==>> Time: 01-02-2024 15:56:04
==>> Type: <class 'AttributeError'>
==>> Value: 'PickUploadAccountWindow' object has no attribute 'updateAllOneRow'
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\PickUploadAccountWindow.py", line 87, in <lambda>
    self.ui.doIt.clicked.connect(lambda: self.saveChanges())
                                         ^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\windows\PickUploadAccountWindow.py", line 148, in saveChanges
    self.updateAllOneRow(self.oneRow, 6, result)
    ^^^^^^^^^^^^^^^^^^^^

==>> Time: 01-02-2024 16:06:18
==>> Type: <class 'TypeError'>
==>> Value: setItem(self, row: int, column: int, item: Optional[QTableWidgetItem]): argument 3 has unexpected type 'str'
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\PickUploadAccountWindow.py", line 87, in <lambda>
    self.ui.doIt.clicked.connect(lambda: self.saveChanges())
                                         ^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\windows\PickUploadAccountWindow.py", line 158, in saveChanges
    self.bigMainTable.setItem(self.oneRow, 7, result)

==>> Time: 01-02-2024 16:07:44
==>> Type: <class 'AttributeError'>
==>> Value: 'builtin_function_or_method' object has no attribute 'close'
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\PickUploadAccountWindow.py", line 87, in <lambda>
    self.ui.doIt.clicked.connect(lambda: self.saveChanges())
                                         ^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\windows\PickUploadAccountWindow.py", line 199, in saveChanges
    self.window.close()
    ^^^^^^^^^^^^^^^^^

==>> Time: 02-02-2024 09:39:59
==>> Type: <class 'FileNotFoundError'>
==>> Value: [WinError 3] The system cannot find the path specified: ''
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\HomeWindow.py", line 140, in run
    for file in os_sorted(os.listdir(uploadFolderPath)):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

==>> Time: 02-02-2024 11:27:40
==>> Type: <class 'NameError'>
==>> Value: name 'indexOfProfileInTable' is not defined
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\HomeWindow.py", line 98, in openQueueWindow
    self.assignThisVideoToProfiles(
  File "d:\Folinas Socials Tool\windows\HomeWindow.py", line 83, in assignThisVideoToProfiles
    indexOfVideoToUpload, indexOfProfileInTable)
                          ^^^^^^^^^^^^^^^^^^^^^

==>> Time: 02-02-2024 11:29:37
==>> Type: <class 'AttributeError'>
==>> Value: 'NoneType' object has no attribute 'findChild'
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\HomeWindow.py", line 98, in openQueueWindow
    self.assignThisVideoToProfiles(
  File "d:\Folinas Socials Tool\windows\HomeWindow.py", line 82, in assignThisVideoToProfiles
    queueWindow.addNewVideoToGridContainsVideo(
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 102, in addNewVideoToGridContainsVideo
    gridContainsVideo = vbox.findChild(QGridLayout, 'gridContainsVideo')
                        ^^^^^^^^^^^^^^

==>> Time: 02-02-2024 11:31:24
==>> Type: <class 'AttributeError'>
==>> Value: 'NoneType' object has no attribute 'findChild'
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\HomeWindow.py", line 98, in openQueueWindow
    self.assignThisVideoToProfiles(
  File "d:\Folinas Socials Tool\windows\HomeWindow.py", line 82, in assignThisVideoToProfiles
    queueWindow.addNewVideoToGridContainsVideo(
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 105, in addNewVideoToGridContainsVideo
    gridContainsVideo = vbox.findChild(QGridLayout, 'gridContainsVideo')
                        ^^^^^^^^^^^^^^

==>> Time: 02-02-2024 14:17:32
==>> Type: <class 'TypeError'>
==>> Value: 'NoneType' object is not subscriptable
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\HomeWindow.py", line 186, in openQueueWindow
    self.assignAssetsLabelToQueue(
  File "d:\Folinas Socials Tool\windows\HomeWindow.py", line 150, in assignAssetsLabelToQueue
    ownerid = record[2]
              ~~~~~~^^^

==>> Time: 02-02-2024 16:07:32
==>> Type: <class 'AttributeError'>
==>> Value: 'QTableWidget' object has no attribute 'unique_arr'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 296, in <lambda>
    table.contextMenuEvent = lambda event: customMenu(
                                           ^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 238, in customMenu
    if index.isValid() and len(table.unique_arr) == 1:
                               ^^^^^^^^^^^^^^^^

==>> Time: 03-02-2024 08:41:13
==>> Type: <class 'TypeError'>
==>> Value: 'NoneType' object is not subscriptable
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 285, in <lambda>
    lambda: self.startThisWorkerNow(indexAsset, startWorker))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 41, in startThisWorkerNow
    self.uploadTask = StaffUpload(
                      ^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 35, in __init__
    ownerid = record[2]
              ~~~~~~^^^

==>> Time: 03-02-2024 08:45:47
==>> Type: <class 'TypeError'>
==>> Value: 'NoneType' object is not subscriptable
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 285, in <lambda>
    lambda: self.startThisWorkerNow(indexAsset, startWorker))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 41, in startThisWorkerNow
    self.uploadTask = StaffUpload(
                      ^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 35, in __init__
    ownerid = record[2]
              ~~~~~~^^^

==>> Time: 03-02-2024 08:47:09
==>> Type: <class 'TypeError'>
==>> Value: 'NoneType' object is not subscriptable
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 285, in <lambda>
    lambda: self.startThisWorkerNow(indexAsset, startWorker))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 41, in startThisWorkerNow
    self.uploadTask = StaffUpload(
                      ^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 36, in __init__
    ownerid = record[2]
              ~~~~~~^^^

==>> Time: 03-02-2024 08:56:53
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: unknown error: cannot connect to chrome at 127.0.0.1:10034
from session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 114.0.5735.45
Stacktrace:
Backtrace:
	Ordinal0 [0x00432733+2434867]
	Ordinal0 [0x003C07A1+1968033]
	Ordinal0 [0x002AC678+837240]
	Ordinal0 [0x002CCAC3+969411]
	Ordinal0 [0x002C60DB+942299]
	Ordinal0 [0x002C5EA6+941734]
	Ordinal0 [0x002F90B0+1151152]
	Ordinal0 [0x002F8D0A+1150218]
	Ordinal0 [0x002F4256+1131094]
	Ordinal0 [0x002CE840+976960]
	Ordinal0 [0x002CF736+980790]
	GetHandleVerifier [0x006A3C72+2515426]
	GetHandleVerifier [0x0069702F+2463135]
	GetHandleVerifier [0x004D522A+620442]
	GetHandleVerifier [0x004D4016+615814]
	Ordinal0 [0x003C707B+1994875]
	Ordinal0 [0x003CB938+2013496]
	Ordinal0 [0x003CBA25+2013733]
	Ordinal0 [0x003D4DE1+2051553]
	BaseThreadInitThunk [0x7667FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77C27C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77C27C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 50, in run
    driver = startBrowserFromUore(
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 657, in startBrowserFromUore
    driver = openBrowser(ACTION_FOR_BROWSER_OPEN, int(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\ControlBrowser.py", line 270, in openBrowser
    driver = Chrome(service=Service(web_driver_path), options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 03-02-2024 09:11:38
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: unknown error: cannot connect to chrome at 127.0.0.1:22599
from session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 114.0.5735.45
Stacktrace:
Backtrace:
	Ordinal0 [0x00432733+2434867]
	Ordinal0 [0x003C07A1+1968033]
	Ordinal0 [0x002AC678+837240]
	Ordinal0 [0x002CCAC3+969411]
	Ordinal0 [0x002C60DB+942299]
	Ordinal0 [0x002C5EA6+941734]
	Ordinal0 [0x002F90B0+1151152]
	Ordinal0 [0x002F8D0A+1150218]
	Ordinal0 [0x002F4256+1131094]
	Ordinal0 [0x002CE840+976960]
	Ordinal0 [0x002CF736+980790]
	GetHandleVerifier [0x006A3C72+2515426]
	GetHandleVerifier [0x0069702F+2463135]
	GetHandleVerifier [0x004D522A+620442]
	GetHandleVerifier [0x004D4016+615814]
	Ordinal0 [0x003C707B+1994875]
	Ordinal0 [0x003CB938+2013496]
	Ordinal0 [0x003CBA25+2013733]
	Ordinal0 [0x003D4DE1+2051553]
	BaseThreadInitThunk [0x7667FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77C27C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77C27C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 51, in run
    driver = startBrowserFromUore(
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 658, in startBrowserFromUore
    driver = openBrowser(ACTION_FOR_BROWSER_OPEN, int(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\ControlBrowser.py", line 270, in openBrowser
    driver = Chrome(service=Service(web_driver_path), options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 03-02-2024 09:13:00
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: unknown error: cannot connect to chrome at 127.0.0.1:41862
from session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 114.0.5735.45
Stacktrace:
Backtrace:
	Ordinal0 [0x00432733+2434867]
	Ordinal0 [0x003C07A1+1968033]
	Ordinal0 [0x002AC678+837240]
	Ordinal0 [0x002CCAC3+969411]
	Ordinal0 [0x002C60DB+942299]
	Ordinal0 [0x002C5EA6+941734]
	Ordinal0 [0x002F90B0+1151152]
	Ordinal0 [0x002F8D0A+1150218]
	Ordinal0 [0x002F4256+1131094]
	Ordinal0 [0x002CE840+976960]
	Ordinal0 [0x002CF736+980790]
	GetHandleVerifier [0x006A3C72+2515426]
	GetHandleVerifier [0x0069702F+2463135]
	GetHandleVerifier [0x004D522A+620442]
	GetHandleVerifier [0x004D4016+615814]
	Ordinal0 [0x003C707B+1994875]
	Ordinal0 [0x003CB938+2013496]
	Ordinal0 [0x003CBA25+2013733]
	Ordinal0 [0x003D4DE1+2051553]
	BaseThreadInitThunk [0x7667FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77C27C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77C27C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 51, in run
    driver = startBrowserFromUore(
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 658, in startBrowserFromUore
    driver = openBrowser(ACTION_FOR_BROWSER_OPEN, int(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\ControlBrowser.py", line 270, in openBrowser
    driver = Chrome(service=Service(web_driver_path), options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 03-02-2024 09:14:20
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: unknown error: cannot connect to chrome at 127.0.0.1:11103
from session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 114.0.5735.45
Stacktrace:
Backtrace:
	Ordinal0 [0x00432733+2434867]
	Ordinal0 [0x003C07A1+1968033]
	Ordinal0 [0x002AC678+837240]
	Ordinal0 [0x002CCAC3+969411]
	Ordinal0 [0x002C60DB+942299]
	Ordinal0 [0x002C5EA6+941734]
	Ordinal0 [0x002F90B0+1151152]
	Ordinal0 [0x002F8D0A+1150218]
	Ordinal0 [0x002F4256+1131094]
	Ordinal0 [0x002CE840+976960]
	Ordinal0 [0x002CF736+980790]
	GetHandleVerifier [0x006A3C72+2515426]
	GetHandleVerifier [0x0069702F+2463135]
	GetHandleVerifier [0x004D522A+620442]
	GetHandleVerifier [0x004D4016+615814]
	Ordinal0 [0x003C707B+1994875]
	Ordinal0 [0x003CB938+2013496]
	Ordinal0 [0x003CBA25+2013733]
	Ordinal0 [0x003D4DE1+2051553]
	BaseThreadInitThunk [0x7667FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77C27C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77C27C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 51, in run
    driver = startBrowserFromUore(
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 658, in startBrowserFromUore
    driver = openBrowser(ACTION_FOR_BROWSER_OPEN, int(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\ControlBrowser.py", line 270, in openBrowser
    driver = Chrome(service=Service(web_driver_path), options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 03-02-2024 09:18:38
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: unknown error: cannot connect to chrome at 127.0.0.1:15259
from session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 114.0.5735.45
Stacktrace:
Backtrace:
	Ordinal0 [0x00432733+2434867]
	Ordinal0 [0x003C07A1+1968033]
	Ordinal0 [0x002AC678+837240]
	Ordinal0 [0x002CCAC3+969411]
	Ordinal0 [0x002C60DB+942299]
	Ordinal0 [0x002C5EA6+941734]
	Ordinal0 [0x002F90B0+1151152]
	Ordinal0 [0x002F8D0A+1150218]
	Ordinal0 [0x002F4256+1131094]
	Ordinal0 [0x002CE840+976960]
	Ordinal0 [0x002CF736+980790]
	GetHandleVerifier [0x006A3C72+2515426]
	GetHandleVerifier [0x0069702F+2463135]
	GetHandleVerifier [0x004D522A+620442]
	GetHandleVerifier [0x004D4016+615814]
	Ordinal0 [0x003C707B+1994875]
	Ordinal0 [0x003CB938+2013496]
	Ordinal0 [0x003CBA25+2013733]
	Ordinal0 [0x003D4DE1+2051553]
	BaseThreadInitThunk [0x7667FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77C27C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77C27C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 51, in run
    driver = startBrowserFromUore(
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 659, in startBrowserFromUore
    driver = openBrowser(ACTION_FOR_BROWSER_OPEN, int(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\ControlBrowser.py", line 270, in openBrowser
    driver = Chrome(service=Service(web_driver_path), options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 03-02-2024 09:19:22
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: unknown error: cannot connect to chrome at 127.0.0.1:7822
from session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 114.0.5735.45
Stacktrace:
Backtrace:
	Ordinal0 [0x00432733+2434867]
	Ordinal0 [0x003C07A1+1968033]
	Ordinal0 [0x002AC678+837240]
	Ordinal0 [0x002CCAC3+969411]
	Ordinal0 [0x002C60DB+942299]
	Ordinal0 [0x002C5EA6+941734]
	Ordinal0 [0x002F90B0+1151152]
	Ordinal0 [0x002F8D0A+1150218]
	Ordinal0 [0x002F4256+1131094]
	Ordinal0 [0x002CE840+976960]
	Ordinal0 [0x002CF736+980790]
	GetHandleVerifier [0x006A3C72+2515426]
	GetHandleVerifier [0x0069702F+2463135]
	GetHandleVerifier [0x004D522A+620442]
	GetHandleVerifier [0x004D4016+615814]
	Ordinal0 [0x003C707B+1994875]
	Ordinal0 [0x003CB938+2013496]
	Ordinal0 [0x003CBA25+2013733]
	Ordinal0 [0x003D4DE1+2051553]
	BaseThreadInitThunk [0x7667FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77C27C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77C27C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 51, in run
    driver = startBrowserFromUore(
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 659, in startBrowserFromUore
    driver = openBrowser(ACTION_FOR_BROWSER_OPEN, int(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\ControlBrowser.py", line 270, in openBrowser
    driver = Chrome(service=Service(web_driver_path), options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 03-02-2024 09:20:11
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: unknown error: cannot connect to chrome at 127.0.0.1:7822
from session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 114.0.5735.45
Stacktrace:
Backtrace:
	Ordinal0 [0x00432733+2434867]
	Ordinal0 [0x003C07A1+1968033]
	Ordinal0 [0x002AC678+837240]
	Ordinal0 [0x002CCAC3+969411]
	Ordinal0 [0x002C60DB+942299]
	Ordinal0 [0x002C5EA6+941734]
	Ordinal0 [0x002F90B0+1151152]
	Ordinal0 [0x002F8D0A+1150218]
	Ordinal0 [0x002F4256+1131094]
	Ordinal0 [0x002CE840+976960]
	Ordinal0 [0x002CF736+980790]
	GetHandleVerifier [0x006A3C72+2515426]
	GetHandleVerifier [0x0069702F+2463135]
	GetHandleVerifier [0x004D522A+620442]
	GetHandleVerifier [0x004D4016+615814]
	Ordinal0 [0x003C707B+1994875]
	Ordinal0 [0x003CB938+2013496]
	Ordinal0 [0x003CBA25+2013733]
	Ordinal0 [0x003D4DE1+2051553]
	BaseThreadInitThunk [0x7667FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77C27C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77C27C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 51, in run
    driver = startBrowserFromUore(
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 659, in startBrowserFromUore
    driver = openBrowser(ACTION_FOR_BROWSER_OPEN, int(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\ControlBrowser.py", line 270, in openBrowser
    driver = Chrome(service=Service(web_driver_path), options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 03-02-2024 09:30:43
==>> Type: <class 'AttributeError'>
==>> Value: 'QueueWindow' object has no attribute 'browsersId'
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 67, in addNewBrowserToGridScreen
    self.browsersId.append(processId)
    ^^^^^^^^^^^^^^^

==>> Time: 03-02-2024 09:47:17
==>> Type: <class 'AttributeError'>
==>> Value: 'QueueWindow' object has no attribute 'driver'
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 321, in <lambda>
    lambda: self.stopThisWorkerNow(indexAsset, startWorker, id_ixbrowser))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 41, in stopThisWorkerNow
    "profile_id": self.driver.profile_id
                  ^^^^^^^^^^^

==>> Time: 03-02-2024 10:03:08
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: disconnected: Unable to receive message from renderer
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=114.0.5735.45)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x01036E73+48323]
	(No symbol) [0x00FC9661]
	(No symbol) [0x00ED5308]
	(No symbol) [0x00EC8395]
	(No symbol) [0x00EC829C]
	(No symbol) [0x00EC6ED6]
	(No symbol) [0x00EC7638]
	(No symbol) [0x00ED6B02]
	(No symbol) [0x00F2D0A1]
	(No symbol) [0x00F1A8DC]
	(No symbol) [0x00F2CAC2]
	(No symbol) [0x00F1A6D6]
	(No symbol) [0x00EF847C]
	(No symbol) [0x00EF957D]
	GetHandleVerifier [0x0129FD5D+2575277]
	GetHandleVerifier [0x012DF86E+2836158]
	GetHandleVerifier [0x012D96DC+2811180]
	GetHandleVerifier [0x010C41B0+626688]
	(No symbol) [0x00FD314C]
	(No symbol) [0x00FCF4B8]
	(No symbol) [0x00FCF59B]
	(No symbol) [0x00FC21B7]
	BaseThreadInitThunk [0x7667FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77C27C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77C27C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 67, in run
    browser.get('https://business.facebook.com/latest/home')
  File "d:\Folinas Socials Tool\core\SeleniumFunctions.py", line 39, in get
    self.driver.get(url)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 03-02-2024 10:22:02
==>> Type: <class 'FileNotFoundError'>
==>> Value: [Errno 2] No such file or directory: 'data/settingPlaform.json'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 69, in run
    self.uploadFacebook(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 87, in uploadFacebook
    with open('data/settingPlaform.json', 'r+') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

==>> Time: 03-02-2024 10:22:58
==>> Type: <class 'FileNotFoundError'>
==>> Value: [Errno 2] No such file or directory: '/data/settingPlaform.json'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 69, in run
    self.uploadFacebook(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 87, in uploadFacebook
    with open('/data/settingPlaform.json', 'r+') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

==>> Time: 03-02-2024 10:23:53
==>> Type: <class 'json.decoder.JSONDecodeError'>
==>> Value: Expecting property name enclosed in double quotes: line 2 column 2 (char 3)
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 69, in run
    self.uploadFacebook(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 88, in uploadFacebook
    data = json.load(f)
           ^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^

==>> Time: 03-02-2024 10:24:48
==>> Type: <class 'json.decoder.JSONDecodeError'>
==>> Value: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 69, in run
    self.uploadFacebook(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 88, in uploadFacebook
    data = json.load(f)
           ^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^

==>> Time: 03-02-2024 10:25:36
==>> Type: <class 'TypeError'>
==>> Value: the JSON object must be str, bytes or bytearray, not TextIOWrapper
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 69, in run
    self.uploadFacebook(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 88, in uploadFacebook
    data = json.loads(f)
           ^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '

==>> Time: 03-02-2024 10:26:58
==>> Type: <class 'FileNotFoundError'>
==>> Value: [Errno 2] No such file or directory: './last_location/settingPlatform.json'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 69, in run
    self.uploadFacebook(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 88, in uploadFacebook
    f = open('./last_location/settingPlatform.json', 'r')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

==>> Time: 03-02-2024 10:27:24
==>> Type: <class 'json.decoder.JSONDecodeError'>
==>> Value: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 69, in run
    self.uploadFacebook(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 89, in uploadFacebook
    data = json.load(f)
           ^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^

==>> Time: 03-02-2024 10:36:26
==>> Type: <class 'TypeError'>
==>> Value: StaffUpload.update_slashState_signal[int, str] signal has 2 argument(s) but 1 provided
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 56, in run
    self.update_slashState_signal.emit(

==>> Time: 03-02-2024 11:04:53
==>> Type: <class 'TypeError'>
==>> Value: StaffUpload.__reelsFacebook() missing 1 required positional argument: 'indexVideo'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 75, in run
    self.uploadFacebook(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 251, in uploadFacebook
    self.__reelsFacebook(browser)

==>> Time: 03-02-2024 11:15:23
==>> Type: <class 'TypeError'>
==>> Value: StaffUpload.update_slashState_signal[int, str] signal has 2 argument(s) but 1 provided
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 75, in run
    self.uploadFacebook(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 459, in uploadFacebook
    self.__reelsFacebook(browser, indexVideo)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 196, in __reelsFacebook
    self.update_slashState_signal.emit('Upload xong..')

==>> Time: 03-02-2024 11:28:28
==>> Type: <class 'selenium.common.exceptions.ElementClickInterceptedException'>
==>> Value: Message: element click intercepted: Element <div class="x1xqt7ti x1fvot60 xk50ysn xxio538 x1heor9g xuxw1ft x6ikm8r x10wlt62 xlyipyv x1h4wwuj xeuugli">...</div> is not clickable at point (575, 68). Other element would receive the click: <div aria-level="4" class="x1xqt7ti xsuwoey x63nzvj xbsr9hj x1yc453h xuxw1ft x6ikm8r x10wlt62 xlyipyv x1h4wwuj x117nqv4 xeuugli" id="js_1h" role="heading">...</div>
  (Session info: chrome=114.0.5735.45)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x01036E73+48323]
	(No symbol) [0x00FC9661]
	(No symbol) [0x00ED5308]
	(No symbol) [0x00F05202]
	(No symbol) [0x00F03D38]
	(No symbol) [0x00F0253B]
	(No symbol) [0x00F0193E]
	(No symbol) [0x00EFA0FC]
	(No symbol) [0x00F1A8DC]
	(No symbol) [0x00EF9BD6]
	(No symbol) [0x00F1AC34]
	(No symbol) [0x00F2CAC2]
	(No symbol) [0x00F1A6D6]
	(No symbol) [0x00EF847C]
	(No symbol) [0x00EF957D]
	GetHandleVerifier [0x0129FD5D+2575277]
	GetHandleVerifier [0x012DF86E+2836158]
	GetHandleVerifier [0x012D96DC+2811180]
	GetHandleVerifier [0x010C41B0+626688]
	(No symbol) [0x00FD314C]
	(No symbol) [0x00FCF4B8]
	(No symbol) [0x00FCF59B]
	(No symbol) [0x00FC21B7]
	BaseThreadInitThunk [0x7667FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77C27C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77C27C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 75, in run
    self.uploadFacebook(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 492, in uploadFacebook
    self.__reelsFacebook(browser, indexVideo)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 365, in __reelsFacebook
    publicBtn.click()
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 93, in click
    self._execute(Command.CLICK_ELEMENT)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 394, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 03-02-2024 11:59:20
==>> Type: <class 'selenium.common.exceptions.NoSuchWindowException'>
==>> Value: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=114.0.5735.45)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x01036E73+48323]
	(No symbol) [0x00FC9661]
	(No symbol) [0x00ED5308]
	(No symbol) [0x00EBD243]
	(No symbol) [0x00F1E51B]
	(No symbol) [0x00F2C613]
	(No symbol) [0x00F1A6D6]
	(No symbol) [0x00EF847C]
	(No symbol) [0x00EF957D]
	GetHandleVerifier [0x0129FD5D+2575277]
	GetHandleVerifier [0x012DF86E+2836158]
	GetHandleVerifier [0x012D96DC+2811180]
	GetHandleVerifier [0x010C41B0+626688]
	(No symbol) [0x00FD314C]
	(No symbol) [0x00FCF4B8]
	(No symbol) [0x00FCF59B]
	(No symbol) [0x00FC21B7]
	BaseThreadInitThunk [0x7667FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77C27C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77C27C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 75, in run
    self.uploadFacebook(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 513, in uploadFacebook
    self.__reelsFacebook(browser, indexVideo)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 368, in __reelsFacebook
    hbtn.click()
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 93, in click
    self._execute(Command.CLICK_ELEMENT)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 394, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 03-02-2024 12:45:42
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: unknown error: cannot connect to chrome at 127.0.0.1:12818
from session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 114.0.5735.45
Stacktrace:
Backtrace:
	Ordinal0 [0x00432733+2434867]
	Ordinal0 [0x003C07A1+1968033]
	Ordinal0 [0x002AC678+837240]
	Ordinal0 [0x002CCAC3+969411]
	Ordinal0 [0x002C60DB+942299]
	Ordinal0 [0x002C5EA6+941734]
	Ordinal0 [0x002F90B0+1151152]
	Ordinal0 [0x002F8D0A+1150218]
	Ordinal0 [0x002F4256+1131094]
	Ordinal0 [0x002CE840+976960]
	Ordinal0 [0x002CF736+980790]
	GetHandleVerifier [0x006A3C72+2515426]
	GetHandleVerifier [0x0069702F+2463135]
	GetHandleVerifier [0x004D522A+620442]
	GetHandleVerifier [0x004D4016+615814]
	Ordinal0 [0x003C707B+1994875]
	Ordinal0 [0x003CB938+2013496]
	Ordinal0 [0x003CBA25+2013733]
	Ordinal0 [0x003D4DE1+2051553]
	BaseThreadInitThunk [0x7667FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77C27C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77C27C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 921, in run
    driver = startBrowserFromUore(
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 1154, in startBrowserFromUore
    driver = openBrowser(ACTION_FOR_BROWSER_OPEN, int(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\ControlBrowser.py", line 270, in openBrowser
    driver = Chrome(service=Service(web_driver_path), options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 03-02-2024 13:38:05
==>> Type: <class 'TypeError'>
==>> Value: StaffUpload.paste_content() missing 1 required positional argument: 'content'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 79, in run
    self.uploadYoutube(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 656, in uploadYoutube
    self.__shortsYT(browser, indexVideo)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 543, in __shortsYT
    self.paste_content(desc_textbox, data[1])

==>> Time: 03-02-2024 13:41:51
==>> Type: <class 'UnboundLocalError'>
==>> Value: cannot access local variable 'thumb_path' where it is not associated with a value
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 79, in run
    self.uploadYoutube(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 658, in uploadYoutube
    self.__shortsYT(browser, indexVideo)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 547, in __shortsYT
    print(f"==>> thumb_path: {thumb_path}")
                              ^^^^^^^^^^

==>> Time: 03-02-2024 13:43:14
==>> Type: <class 'UnboundLocalError'>
==>> Value: cannot access local variable 'thumb_path' where it is not associated with a value
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 79, in run
    self.uploadYoutube(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 659, in uploadYoutube
    self.__shortsYT(browser, indexVideo)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 547, in __shortsYT
    print(f"==>> thumb_path: {thumb_path}")
                              ^^^^^^^^^^

==>> Time: 03-02-2024 13:44:11
==>> Type: <class 'selenium.common.exceptions.JavascriptException'>
==>> Value: Message: javascript error: Cannot read properties of null (reading 'scrollIntoView')
  (Session info: chrome=114.0.5735.45)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x01036E73+48323]
	(No symbol) [0x00FC9661]
	(No symbol) [0x00ED5308]
	(No symbol) [0x00ED8751]
	(No symbol) [0x00EDA14B]
	(No symbol) [0x00F2D419]
	(No symbol) [0x00F1A8DC]
	(No symbol) [0x00F2CAC2]
	(No symbol) [0x00F1A6D6]
	(No symbol) [0x00EF847C]
	(No symbol) [0x00EF957D]
	GetHandleVerifier [0x0129FD5D+2575277]
	GetHandleVerifier [0x012DF86E+2836158]
	GetHandleVerifier [0x012D96DC+2811180]
	GetHandleVerifier [0x010C41B0+626688]
	(No symbol) [0x00FD314C]
	(No symbol) [0x00FCF4B8]
	(No symbol) [0x00FCF59B]
	(No symbol) [0x00FC21B7]
	BaseThreadInitThunk [0x7667FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77C27C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77C27C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 79, in run
    self.uploadYoutube(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 659, in uploadYoutube
    self.__shortsYT(browser, indexVideo)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 570, in __shortsYT
    browser.scrollToElement(tags_container)
  File "d:\Folinas Socials Tool\core\SeleniumFunctions.py", line 76, in scrollToElement
    self.driver.execute_script(
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 03-02-2024 13:58:18
==>> Type: <class 'selenium.common.exceptions.ElementClickInterceptedException'>
==>> Value: Message: element click intercepted: Element <tp-yt-paper-radio-button name="VIDEO_MADE_FOR_KIDS_NOT_MFK" class="style-scope ytkc-made-for-kids-select" role="radio" tabindex="-1" toggles="" aria-checked="false" aria-disabled="false" aria-selected="false">...</tp-yt-paper-radio-button> is not clickable at point (527, 416). Other element would receive the click: <div class="dialog-scrim style-scope ytcp-uploads-dialog"></div>
  (Session info: chrome=114.0.5735.45)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x01036E73+48323]
	(No symbol) [0x00FC9661]
	(No symbol) [0x00ED5308]
	(No symbol) [0x00F05202]
	(No symbol) [0x00F03D38]
	(No symbol) [0x00F0253B]
	(No symbol) [0x00F0193E]
	(No symbol) [0x00EFA0FC]
	(No symbol) [0x00F1A8DC]
	(No symbol) [0x00EF9BD6]
	(No symbol) [0x00F1AC34]
	(No symbol) [0x00F2CAC2]
	(No symbol) [0x00F1A6D6]
	(No symbol) [0x00EF847C]
	(No symbol) [0x00EF957D]
	GetHandleVerifier [0x0129FD5D+2575277]
	GetHandleVerifier [0x012DF86E+2836158]
	GetHandleVerifier [0x012D96DC+2811180]
	GetHandleVerifier [0x010C41B0+626688]
	(No symbol) [0x00FD314C]
	(No symbol) [0x00FCF4B8]
	(No symbol) [0x00FCF59B]
	(No symbol) [0x00FC21B7]
	BaseThreadInitThunk [0x7667FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77C27C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77C27C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 79, in run
    self.uploadYoutube(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 662, in uploadYoutube
    self.__shortsYT(browser, indexVideo)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 562, in __shortsYT
    kids_section.click()
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 93, in click
    self._execute(Command.CLICK_ELEMENT)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 394, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 03-02-2024 14:16:57
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: unknown error: cannot connect to chrome at 127.0.0.1:50776
from session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 114.0.5735.45
Stacktrace:
Backtrace:
	Ordinal0 [0x00432733+2434867]
	Ordinal0 [0x003C07A1+1968033]
	Ordinal0 [0x002AC678+837240]
	Ordinal0 [0x002CCAC3+969411]
	Ordinal0 [0x002C60DB+942299]
	Ordinal0 [0x002C5EA6+941734]
	Ordinal0 [0x002F90B0+1151152]
	Ordinal0 [0x002F8D0A+1150218]
	Ordinal0 [0x002F4256+1131094]
	Ordinal0 [0x002CE840+976960]
	Ordinal0 [0x002CF736+980790]
	GetHandleVerifier [0x006A3C72+2515426]
	GetHandleVerifier [0x0069702F+2463135]
	GetHandleVerifier [0x004D522A+620442]
	GetHandleVerifier [0x004D4016+615814]
	Ordinal0 [0x003C707B+1994875]
	Ordinal0 [0x003CB938+2013496]
	Ordinal0 [0x003CBA25+2013733]
	Ordinal0 [0x003D4DE1+2051553]
	BaseThreadInitThunk [0x7667FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77C27C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77C27C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 802, in run
    driver = startBrowserFromUore(
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 1304, in startBrowserFromUore
    driver = openBrowser(ACTION_FOR_BROWSER_OPEN, int(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\ControlBrowser.py", line 270, in openBrowser
    driver = Chrome(service=Service(web_driver_path), options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 03-02-2024 15:54:28
==>> Type: <class 'KeyError'>
==>> Value: '3'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 82, in run
    self.uploadTwitter(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 819, in uploadTwitter
    self.__twitter(browser, indexVideo)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 722, in __twitter
    if month.text == self.getMonth(date_s[0]):
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 815, in getMonth
    return data[month]
           ~~~~^^^^^^^

==>> Time: 03-02-2024 16:19:51
==>> Type: <class 'AttributeError'>
==>> Value: 'NoneType' object has no attribute 'send_keys'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 85, in run
    self.uploadInstagram(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 841, in uploadInstagram
    self.__twitter(browser, indexVideo)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 697, in __twitter
    inp.send_keys(data[4])
    ^^^^^^^^^^^^^

==>> Time: 03-02-2024 16:20:20
==>> Type: <class 'AttributeError'>
==>> Value: 'NoneType' object has no attribute 'click'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 85, in run
    self.uploadInstagram(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 841, in uploadInstagram
    self.__instagram(browser, indexVideo)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 809, in __instagram
    create.click()
    ^^^^^^^^^^^^

==>> Time: 03-02-2024 16:21:16
==>> Type: <class 'AttributeError'>
==>> Value: 'NoneType' object has no attribute 'click'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 85, in run
    self.uploadInstagram(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 841, in uploadInstagram
    self.__instagram(browser, indexVideo)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 809, in __instagram
    create.click()
    ^^^^^^^^^^^^

==>> Time: 03-02-2024 16:22:32
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: unknown error: cannot connect to chrome at 127.0.0.1:57875
from session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 114.0.5735.45
Stacktrace:
Backtrace:
	Ordinal0 [0x00432733+2434867]
	Ordinal0 [0x003C07A1+1968033]
	Ordinal0 [0x002AC678+837240]
	Ordinal0 [0x002CCAC3+969411]
	Ordinal0 [0x002C60DB+942299]
	Ordinal0 [0x002C5EA6+941734]
	Ordinal0 [0x002F90B0+1151152]
	Ordinal0 [0x002F8D0A+1150218]
	Ordinal0 [0x002F4256+1131094]
	Ordinal0 [0x002CE840+976960]
	Ordinal0 [0x002CF736+980790]
	GetHandleVerifier [0x006A3C72+2515426]
	GetHandleVerifier [0x0069702F+2463135]
	GetHandleVerifier [0x004D522A+620442]
	GetHandleVerifier [0x004D4016+615814]
	Ordinal0 [0x003C707B+1994875]
	Ordinal0 [0x003CB938+2013496]
	Ordinal0 [0x003CBA25+2013733]
	Ordinal0 [0x003D4DE1+2051553]
	BaseThreadInitThunk [0x7667FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77C27C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77C27C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 59, in run
    driver = startBrowserFromUore(
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 1468, in startBrowserFromUore
    driver = openBrowser(ACTION_FOR_BROWSER_OPEN, int(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\ControlBrowser.py", line 270, in openBrowser
    driver = Chrome(service=Service(web_driver_path), options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "c:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 03-02-2024 16:22:51
==>> Type: <class 'AttributeError'>
==>> Value: 'NoneType' object has no attribute 'send_keys'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 85, in run
    self.uploadInstagram(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 841, in uploadInstagram
    self.__instagram(browser, indexVideo)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 814, in __instagram
    inp.send_keys(data[4])
    ^^^^^^^^^^^^^

==>> Time: 03-02-2024 16:23:56
==>> Type: <class 'AttributeError'>
==>> Value: 'NoneType' object has no attribute 'send_keys'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 85, in run
    self.uploadInstagram(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 841, in uploadInstagram
    self.__instagram(browser, indexVideo)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 814, in __instagram
    inp.send_keys(data[4])
    ^^^^^^^^^^^^^

==>> Time: 05-02-2024 08:43:57
==>> Type: <class 'requests.exceptions.ConnectionError'>
==>> Value: HTTPConnectionPool(host='127.0.0.1', port=53200): Max retries exceeded with url: /api/v2/profile-close (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C5C23D6250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 400, in <lambda>
    lambda: self.stopThisWorkerNow(indexAsset, startWorker, id_ixbrowser))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 54, in stopThisWorkerNow
    requests.post(action, json=paras)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)

==>> Time: 05-02-2024 08:44:01
==>> Type: <class 'requests.exceptions.ConnectionError'>
==>> Value: HTTPConnectionPool(host='127.0.0.1', port=53200): Max retries exceeded with url: /api/v2/profile-close (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C5C23F0C10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 400, in <lambda>
    lambda: self.stopThisWorkerNow(indexAsset, startWorker, id_ixbrowser))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 54, in stopThisWorkerNow
    requests.post(action, json=paras)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)

==>> Time: 05-02-2024 08:44:05
==>> Type: <class 'requests.exceptions.ConnectionError'>
==>> Value: HTTPConnectionPool(host='127.0.0.1', port=53200): Max retries exceeded with url: /api/v2/profile-close (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C5C23D6210>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 400, in <lambda>
    lambda: self.stopThisWorkerNow(indexAsset, startWorker, id_ixbrowser))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 54, in stopThisWorkerNow
    requests.post(action, json=paras)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)

==>> Time: 05-02-2024 08:45:00
==>> Type: <class 'AttributeError'>
==>> Value: 'NoneType' object has no attribute 'click'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 86, in run
    self.uploadInstagram(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 1117, in uploadInstagram
    self.__instagram(browser, indexVideo)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 1065, in __instagram
    create.click()
    ^^^^^^^^^^^^

==>> Time: 05-02-2024 08:46:37
==>> Type: <class 'AttributeError'>
==>> Value: 'NoneType' object has no attribute 'click'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 86, in run
    self.uploadInstagram(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 1117, in uploadInstagram
    self.__instagram(browser, indexVideo)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 1065, in __instagram
    create.click()
    ^^^^^^^^^^^^

==>> Time: 05-02-2024 09:03:46
==>> Type: <class 'AttributeError'>
==>> Value: 'NoneType' object has no attribute 'send_keys'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 80, in run
    self.uploadYoutube(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 938, in uploadYoutube
    self.__shortsYT(browser, indexVideo)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 802, in __shortsYT
    browser.find(By.XPATH, "//input[@type='file']").send_keys(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

==>> Time: 05-02-2024 09:04:27
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: unknown error: cannot connect to chrome at 127.0.0.1:15180
from chrome not reachable
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00D76E73+48323]
	(No symbol) [0x00D09661]
	(No symbol) [0x00C151D0]
	(No symbol) [0x00C0B305]
	(No symbol) [0x00C35E08]
	(No symbol) [0x00C30854]
	(No symbol) [0x00C30631]
	(No symbol) [0x00C60DF5]
	(No symbol) [0x00C60ADC]
	(No symbol) [0x00C5A6D6]
	(No symbol) [0x00C3847C]
	(No symbol) [0x00C3957D]
	GetHandleVerifier [0x00FDFD5D+2575277]
	GetHandleVerifier [0x0101F86E+2836158]
	GetHandleVerifier [0x010196DC+2811180]
	GetHandleVerifier [0x00E041B0+626688]
	(No symbol) [0x00D1314C]
	(No symbol) [0x00D0F4B8]
	(No symbol) [0x00D0F59B]
	(No symbol) [0x00D021B7]
	BaseThreadInitThunk [0x7667FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77C27C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77C27C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 60, in run
    driver = startBrowserFromUore(
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 1748, in startBrowserFromUore
    driver = openBrowser(ACTION_FOR_BROWSER_OPEN, int(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\ControlBrowser.py", line 270, in openBrowser
    driver = Chrome(service=Service(web_driver_path), options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 05-02-2024 09:04:39
==>> Type: <class 'AttributeError'>
==>> Value: 'NoneType' object has no attribute 'send_keys'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 80, in run
    self.uploadYoutube(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 938, in uploadYoutube
    self.__shortsYT(browser, indexVideo)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 802, in __shortsYT
    browser.find(By.XPATH, "//input[@type='file']").send_keys(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

==>> Time: 05-02-2024 09:06:00
==>> Type: <class 'selenium.common.exceptions.ElementClickInterceptedException'>
==>> Value: Message: element click intercepted: Element <div class="x1xqt7ti x1fvot60 xk50ysn xxio538 x1heor9g xuxw1ft x6ikm8r x10wlt62 xlyipyv x1h4wwuj xeuugli">...</div> is not clickable at point (146, 174). Other element would receive the click: <input data-friend="new" aria-checked="true" aria-label="Allow gifts" role="switch" aria-describedby="js_7z" class="xjyslct x1ypdohk x5yr21d x17qophe xdj266r x11i5rnm xat24cr x1mh8g0r x1w3u9th x1t137rt x10l6tqk x13vifvy xh8yej3 x1vjfegm" id="js_7y" type="checkbox" value="true" checked="">
  (Session info: chrome=114.0.5735.45)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00D76E73+48323]
	(No symbol) [0x00D09661]
	(No symbol) [0x00C15308]
	(No symbol) [0x00C45202]
	(No symbol) [0x00C43D38]
	(No symbol) [0x00C4253B]
	(No symbol) [0x00C4193E]
	(No symbol) [0x00C3A0FC]
	(No symbol) [0x00C5A8DC]
	(No symbol) [0x00C39BD6]
	(No symbol) [0x00C5AC34]
	(No symbol) [0x00C6CAC2]
	(No symbol) [0x00C5A6D6]
	(No symbol) [0x00C3847C]
	(No symbol) [0x00C3957D]
	GetHandleVerifier [0x00FDFD5D+2575277]
	GetHandleVerifier [0x0101F86E+2836158]
	GetHandleVerifier [0x010196DC+2811180]
	GetHandleVerifier [0x00E041B0+626688]
	(No symbol) [0x00D1314C]
	(No symbol) [0x00D0F4B8]
	(No symbol) [0x00D0F59B]
	(No symbol) [0x00D021B7]
	BaseThreadInitThunk [0x7667FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77C27C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77C27C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 77, in run
    self.uploadFacebook(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 782, in uploadFacebook
    self.__reelsFacebook(browser, indexVideo)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 652, in __reelsFacebook
    publicBtn.click()
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 93, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 394, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 05-02-2024 09:11:33
==>> Type: <class 'KeyError'>
==>> Value: 99
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 403, in <lambda>
    lambda: self.stopThisWorkerNow(indexAsset, startWorker, id_ixbrowser))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 61, in stopThisWorkerNow
    del self.browsersInQueue[id_ixbrowser]
        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^

==>> Time: 05-02-2024 09:11:34
==>> Type: <class 'KeyError'>
==>> Value: 99
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 403, in <lambda>
    lambda: self.stopThisWorkerNow(indexAsset, startWorker, id_ixbrowser))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 61, in stopThisWorkerNow
    del self.browsersInQueue[id_ixbrowser]
        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^

==>> Time: 05-02-2024 09:11:35
==>> Type: <class 'KeyError'>
==>> Value: 99
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 403, in <lambda>
    lambda: self.stopThisWorkerNow(indexAsset, startWorker, id_ixbrowser))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 61, in stopThisWorkerNow
    del self.browsersInQueue[id_ixbrowser]
        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^

==>> Time: 05-02-2024 09:13:20
==>> Type: <class 'TypeError'>
==>> Value: 'NoneType' object is not subscriptable
==>> Traceback:
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 414, in <lambda>
    table.contextMenuEvent = lambda event: customMenuVideos(
                                           ^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 394, in customMenuVideos
    openTheAccount(index.row(), table)
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 50, in openTheAccount
    startBrowserFromUore(
  File "d:\Folinas Socials Tool\core\HomeController.py", line 1721, in startBrowserFromUore
    proxy = record[7]
            ~~~~~~^^^

==>> Time: 05-02-2024 11:58:07
==>> Type: <class 'TypeError'>
==>> Value: 'NoneType' object is not subscriptable
==>> Traceback:
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 414, in <lambda>
    table.contextMenuEvent = lambda event: customMenuVideos(
                                           ^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 394, in customMenuVideos
    openTheAccount(index.row(), table)
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 50, in openTheAccount
    startBrowserFromUore(
  File "d:\Folinas Socials Tool\core\HomeController.py", line 1764, in startBrowserFromUore
    proxy = record[7]
            ~~~~~~^^^

==>> Time: 05-02-2024 13:57:04
==>> Type: <class 'TypeError'>
==>> Value: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 78, in run
    self.uploadFacebook(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 795, in uploadFacebook
    self.__videosFacebook(browser, indexVideo)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 227, in __videosFacebook
    percent = int(uploadSection.get_attribute('aria-valuenow'))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

==>> Time: 05-02-2024 14:08:35
==>> Type: <class 'selenium.common.exceptions.WebDriverException'>
==>> Value: Message: unknown error: cannot connect to chrome at 127.0.0.1:43157
from session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 114.0.5735.45
Stacktrace:
Backtrace:
	Ordinal0 [0x009D2733+2434867]
	Ordinal0 [0x009607A1+1968033]
	Ordinal0 [0x0084C678+837240]
	Ordinal0 [0x0086CAC3+969411]
	Ordinal0 [0x008660DB+942299]
	Ordinal0 [0x00865EA6+941734]
	Ordinal0 [0x008990B0+1151152]
	Ordinal0 [0x00898D0A+1150218]
	Ordinal0 [0x00894256+1131094]
	Ordinal0 [0x0086E840+976960]
	Ordinal0 [0x0086F736+980790]
	GetHandleVerifier [0x00C43C72+2515426]
	GetHandleVerifier [0x00C3702F+2463135]
	GetHandleVerifier [0x00A7522A+620442]
	GetHandleVerifier [0x00A74016+615814]
	Ordinal0 [0x0096707B+1994875]
	Ordinal0 [0x0096B938+2013496]
	Ordinal0 [0x0096BA25+2013733]
	Ordinal0 [0x00974DE1+2051553]
	BaseThreadInitThunk [0x7667FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77C27C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77C27C3E+238]

==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 61, in run
    driver = startBrowserFromUore(
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\HomeController.py", line 1785, in startBrowserFromUore
    driver = openBrowser(ACTION_FOR_BROWSER_OPEN, int(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\ControlBrowser.py", line 270, in openBrowser
    driver = Chrome(service=Service(web_driver_path), options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Folinas Staff\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

==>> Time: 06-02-2024 08:40:42
==>> Type: <class 'sqlite3.OperationalError'>
==>> Value: near "FROM": syntax error
==>> Traceback:
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 317, in <lambda>
    table.contextMenuEvent = lambda event: customMenu(
                                           ^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 309, in customMenu
    deleteTheAccount(index, table)
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 61, in deleteTheAccount
    cursor.execute(f"SELECT FROM profiles WHERE uore=?", (uore,))

==>> Time: 06-02-2024 08:41:44
==>> Type: <class 'sqlite3.OperationalError'>
==>> Value: near "FROM": syntax error
==>> Traceback:
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 318, in <lambda>
    table.contextMenuEvent = lambda event: customMenu(
                                           ^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 310, in customMenu
    deleteTheAccount(index, table)
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 62, in deleteTheAccount
    cursor.execute(f"SELECT FROM profiles WHERE uore=?", (uore,))

==>> Time: 06-02-2024 08:43:21
==>> Type: <class 'sqlite3.OperationalError'>
==>> Value: near "FROM": syntax error
==>> Traceback:
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 319, in <lambda>
    table.contextMenuEvent = lambda event: customMenu(
                                           ^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 311, in customMenu
    deleteTheAccount(index, table)
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 63, in deleteTheAccount
    cursor.execute(f"SELECT FROM profiles WHERE uore=?", (uore,))

==>> Time: 06-02-2024 15:41:47
==>> Type: <class 'AttributeError'>
==>> Value: 'QueueWindow' object has no attribute 'waitThread'
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 404, in <lambda>
    lambda: self.startThisWorkerNow(indexAsset, startWorker, waitForThread, id_ixbrowser))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 147, in startThisWorkerNow
    self.waitThread[indexAsset] = waitForIt()
    ^^^^^^^^^^^^^^^

==>> Time: 06-02-2024 15:41:52
==>> Type: <class 'AttributeError'>
==>> Value: 'QueueWindow' object has no attribute 'waitThread'
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 404, in <lambda>
    lambda: self.startThisWorkerNow(indexAsset, startWorker, waitForThread, id_ixbrowser))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 147, in startThisWorkerNow
    self.waitThread[indexAsset] = waitForIt()
    ^^^^^^^^^^^^^^^

==>> Time: 06-02-2024 15:46:14
==>> Type: <class 'AttributeError'>
==>> Value: 'NoneType' object has no attribute 'click'
==>> Traceback:
  File "d:\Folinas Socials Tool\core\HomeController.py", line 87, in run
    self.uploadInstagram(browser)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 1155, in uploadInstagram
    self.__instagram(browser, indexVideo)
  File "d:\Folinas Socials Tool\core\HomeController.py", line 1076, in __instagram
    nextBtn.click()
    ^^^^^^^^^^^^^

==>> Time: 06-02-2024 15:46:22
==>> Type: <class 'TypeError'>
==>> Value: QueueWindow.stopThisWorkerNow() takes 4 positional arguments but 5 were given
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 425, in <lambda>
    lambda: self.stopThisWorkerNow(indexAsset, startWorker, waitForThread, id_ixbrowser))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

==>> Time: 06-02-2024 15:46:33
==>> Type: <class 'TypeError'>
==>> Value: QueueWindow.stopThisWorkerNow() takes 4 positional arguments but 5 were given
==>> Traceback:
  File "d:\Folinas Socials Tool\windows\QueueWindow.py", line 425, in <lambda>
    lambda: self.stopThisWorkerNow(indexAsset, startWorker, waitForThread, id_ixbrowser))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

==>> Time: 06-02-2024 16:38:17
==>> Type: <class 'TypeError'>
==>> Value: 'NoneType' object is not subscriptable
==>> Traceback:
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 438, in <lambda>
    table.contextMenuEvent = lambda event: customMenuVideos(
                                           ^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 418, in customMenuVideos
    openTheAccount(index.row(), table)
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 50, in openTheAccount
    startBrowserFromUore(
  File "d:\Folinas Socials Tool\core\HomeController.py", line 1758, in startBrowserFromUore
    proxy = record[7]
            ~~~~~~^^^

==>> Time: 06-02-2024 16:38:19
==>> Type: <class 'TypeError'>
==>> Value: 'NoneType' object is not subscriptable
==>> Traceback:
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 438, in <lambda>
    table.contextMenuEvent = lambda event: customMenuVideos(
                                           ^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 418, in customMenuVideos
    openTheAccount(index.row(), table)
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 50, in openTheAccount
    startBrowserFromUore(
  File "d:\Folinas Socials Tool\core\HomeController.py", line 1758, in startBrowserFromUore
    proxy = record[7]
            ~~~~~~^^^

==>> Time: 06-02-2024 16:38:23
==>> Type: <class 'TypeError'>
==>> Value: 'NoneType' object is not subscriptable
==>> Traceback:
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 438, in <lambda>
    table.contextMenuEvent = lambda event: customMenuVideos(
                                           ^^^^^^^^^^^^^^^^^
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 418, in customMenuVideos
    openTheAccount(index.row(), table)
  File "d:\Folinas Socials Tool\core\WidgetsSetup.py", line 50, in openTheAccount
    startBrowserFromUore(
  File "d:\Folinas Socials Tool\core\HomeController.py", line 1758, in startBrowserFromUore
    proxy = record[7]
            ~~~~~~^^^

==>> Time: 24-02-2024 13:16:58
==>> Type: <class 'FileNotFoundError'>
==>> Value: [WinError 3] The system cannot find the path specified: 'D:\\Folinas Socials Tool\\thumucupload'
==>> Traceback:
  File "D:\Folinas Socials Tool\windows\HomeWindow.py", line 344, in run
    for file in os_sorted(os.listdir(uploadFolderPath)):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

==>> Time: 24-02-2024 13:19:33
==>> Type: <class 'IndexError'>
==>> Value: list index out of range
==>> Traceback:
  File "D:\Folinas Socials Tool\windows\BulkScheduleWindow.py", line 126, in applyToMainTableFuncs
    self.applyToThem(self.type)
  File "D:\Folinas Socials Tool\windows\BulkScheduleWindow.py", line 211, in applyToThem
    theTime = structureTime[stt]
              ~~~~~~~~~~~~~^^^^^

==>> Time: 26-02-2024 08:48:02
==>> Type: <class 'FileNotFoundError'>
==>> Value: [WinError 3] The system cannot find the path specified: 'D:\\Folinas Socials Tool\\thumucupload'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 344, in run
    for file in os_sorted(os.listdir(uploadFolderPath)):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

==>> Time: 26-02-2024 09:04:41
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:05:09
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:05:28
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:05:29
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:05:29
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:05:50
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:06:03
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:06:04
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:06:11
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:07:58
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:08:10
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:08:11
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:08:12
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:08:13
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:08:14
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:08:15
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:08:15
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:08:15
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:08:15
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:08:16
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:08:16
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:08:16
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:08:16
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:08:16
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:08:17
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:08:17
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:08:17
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:08:17
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:08:18
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:08:18
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:08:18
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:09:06
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 365, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:10:00
==>> Type: <class 'FileNotFoundError'>
==>> Value: [WinError 3] The system cannot find the path specified: 'D:\\Folinas Socials Tool\\thumucupload'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 344, in run
    for file in os_sorted(os.listdir(uploadFolderPath)):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

==>> Time: 26-02-2024 09:10:11
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 366, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:11:11
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 367, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:12:15
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 367, in run

==>> Time: 26-02-2024 09:12:26
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 367, in run

==>> Time: 26-02-2024 09:12:27
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 367, in run

==>> Time: 26-02-2024 09:12:28
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 367, in run

==>> Time: 26-02-2024 09:13:02
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 367, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:13:03
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 367, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:13:03
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 367, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:13:03
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 367, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:13:03
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 367, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:13:03
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 367, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:13:04
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 367, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:13:04
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 367, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:13:04
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 367, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:13:04
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 367, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:13:04
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 367, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:13:05
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 367, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:22:31
==>> Type: <class 'TypeError'>
==>> Value: loadToTable.pushInfo[str, bytes, str].emit(): argument 2 has unexpected type 'int'
==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\windows\HomeWindow.py", line 367, in run
    self.pushInfo.emit(title, output, absolute_file_path)

==>> Time: 26-02-2024 09:26:46
==>> Type: <class 'selenium.common.exceptions.ElementClickInterceptedException'>
==>> Value: Message: element click intercepted: Element <svg aria-label="New post" class="x1lliihq x1n2onr6 x5n08af" fill="currentColor" height="24" role="img" viewBox="0 0 24 24" width="24">...</svg> is not clickable at point (36, 464). Other element would receive the click: <div class="x1qjc9v5 x9f619 x78zum5 xdt5ytf x1iyjqo2 xl56j7k" style="--fds-black: black; --fds-black-alpha-05: rgba(0, 0, 0, 0.05); --fds-black-alpha-10: rgba(0, 0, 0, 0.1); --fds-black-alpha-15: rgba(0, 0, 0, 0.15); --fds-black-alpha-20: rgba(0, 0, 0, 0.2); --fds-black-alpha-30: rgba(0, 0, 0, 0.3); --fds-black-alpha-40: rgba(0, 0, 0, 0.4); --fds-black-alpha-50: rgba(0, 0, 0, 0.5); --fds-black-alpha-60: rgba(0, 0, 0, 0.6); --fds-black-alpha-80: rgba(0, 0, 0, 0.8); --fds-blue-05: black; --fds-blue-30: black; --fds-blue-40: black; --fds-blue-60: black; --fds-blue-70: black; --fds-blue-80: black; --fds-button-text: black; --fds-comment-background: black; --fds-dark-mode-gray-35: black; --fds-dark-mode-gray-50: black; --fds-dark-mode-gray-70: black; --fds-dark-mode-gray-80: black; --fds-dark-mode-gray-90: black; --fds-dark-mode-gray-100: black; --fds-gray-00: black; --fds-gray-05: black; --fds-gray-10: black; --fds-gray-20: black; --fds-gray-25: black; --fds-gray-30: black; --fds-gray-45: black; --fds-gray-70: black; --fds-gray-80: black; --fds-gray-90: black; --fds-gray-100: black; --fds-green-55: black; --fds-highlight: black; --fds-highlight-cell-background: black; --fds-primary-icon: white; --fds-primary-text: white; --fds-red-55: black; --fds-soft: cubic-bezier(.08,.52,.52,1); --fds-spectrum-aluminum-tint-70: black; --fds-spectrum-blue-gray-tint-70: black; --fds-spectrum-cherry: black; --fds-spectrum-cherry-tint-70: black; --fds-spectrum-grape-tint-70: black; --fds-spectrum-grape-tint-90: black; --fds-spectrum-lemon-dark-1: black; --fds-spectrum-lemon-tint-70: black; --fds-spectrum-lime: black; --fds-spectrum-lime-tint-70: black; --fds-spectrum-orange-tint-70: black; --fds-spectrum-orange-tint-90: black; --fds-spectrum-seafoam-tint-70: black; --fds-spectrum-slate-dark-2: black; --fds-spectrum-slate-tint-70: black; --fds-spectrum-teal: black; --fds-spectrum-teal-dark-1: black; --fds-spectrum-teal-dark-2: black; --fds-spectrum-teal-tint-70: black; --fds-spectrum-teal-tint-90: black; --fds-spectrum-tomato: black; --fds-spectrum-tomato-tint-30: black; --fds-spectrum-tomato-tint-90: black; --fds-strong: cubic-bezier(.12,.8,.32,1); --fds-white: black; --fds-white-alpha-05: rgba(255, 255, 255, 0.05); --fds-white-alpha-10: rgba(255, 255, 255, 0.1); --fds-white-alpha-20: rgba(255, 255, 255, 0.2); --fds-white-alpha-30: rgba(255, 255, 255, 0.3); --fds-white-alpha-40: rgba(255, 255, 255, 0.4); --fds-white-alpha-50: rgba(255, 255, 255, 0.5); --fds-white-alpha-60: rgba(255, 255, 255, 0.6); --fds-white-alpha-80: rgba(255, 255, 255, 0.8); --fds-yellow-20: black; --accent: #0095F6; --always-white: white; --always-black: black; --always-dark-gradient: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0.6)); --always-dark-overlay: rgba(0, 0, 0, 0.4); --always-light-overlay: rgba(255, 255, 255, 0.4); --always-gray-40: #65676B; --always-gray-75: #BCC0C4; --always-gray-95: #F0F2F5; --attachment-footer-background: rgba(255,255,255,0.1); --background-deemphasized: rgba(255,255,255,0.1); --badge-background-color-blue: var(--accent); --badge-background-color-dark-gray: var(--secondary-icon); --badge-background-color-gray: var(--disabled-icon); --badge-background-color-green: var(--positive); --badge-background-color-light-blue: var(--highlight-bg); --badge-background-color-red: var(--notification-badge); --badge-background-color-yellow: var(--base-lemon); --base-blue: #1877F2; --base-cherry: #F3425F; --base-grape: #9360F7; --base-lemon: #F7B928; --base-lime: #45BD62; --base-pink: #FF66BF; --base-seafoam: #54C7EC; --base-teal: #2ABBA7; --base-tomato: #FB724B; --text-badge-info-background: hsl(214, 100%, 59%); --text-badge-success-background: #31A24C; --text-badge-attention-background: hsl(40, 89%, 52%); --text-badge-critical-background: #e41e3f; --blue-link: #00376B; --border-focused: #8A8D91; --card-background: #242526; --card-background-flat: #323436; --comment-background: #3A3B3C; --comment-footer-background: #4E4F50; --dataviz-primary-1: rgb(48,200,180); --disabled-button-background: rgba(255, 255, 255, 0.2); --disabled-button-text: rgba(255, 255, 255, 0.3); --disabled-icon: rgba(255, 255, 255, 0.3); --disabled-text: rgba(255, 255, 255, 0.3); --divider: #3E4042; --event-date: #F3425F; --fb-wordmark: #FFFFFF; --fb-logo: #0866FF; --filter-accent: invert(40%) sepia(52%) saturate(200%) saturate(200%) saturate(200%) saturate(189%) hue-rotate(191deg) brightness(103%) contrast(102%); --filter-always-white: invert(100%); --filter-disabled-icon: invert(100%) opacity(30%); --filter-placeholder-icon: invert(59%) sepia(11%) saturate(200%) saturate(135%) hue-rotate(176deg) brightness(96%) contrast(94%); --filter-primary-accent: invert(40%) sepia(52%) saturate(200%) saturate(200%) saturate(200%) saturate(189%) hue-rotate(191deg) brightness(103%) contrast(102%); --filter-primary-icon: invert(89%) sepia(6%) hue-rotate(185deg); --filter-secondary-icon: invert(62%) sepia(98%) saturate(12%) hue-rotate(175deg) brightness(90%) contrast(96%); --filter-warning-icon: invert(77%) sepia(29%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(128%) hue-rotate(359deg) brightness(102%) contrast(107%); --filter-blue-link-icon: invert(73%) sepia(29%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(103.25%) hue-rotate(189deg) brightness(101%) contrast(101%); --filter-positive: invert(37%) sepia(61%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(115%) hue-rotate(91deg) brightness(97%) contrast(105%); --filter-negative: invert(25%) sepia(33%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(110%) hue-rotate(345deg) brightness(132%) contrast(96%); --focus-ring-blue: #1877F2; --glimmer-spinner-icon: white; --hero-banner-background: #E85D07; --hosted-view-selected-state: rgba(45, 136, 255, 0.1); --highlight-bg: rgba(24, 119, 242, .31); --hover-overlay: rgba(255, 255, 255, 0.1); --inverse-text: var(--always-white); --list-cell-chevron: #B0B3B8; --media-hover: rgba(68, 73, 80, 0.15); --media-inner-border: rgba(255, 255, 255, 0.05); --media-outer-border: #33363A; --media-pressed: rgba(68, 73, 80, 0.35); --messenger-card-background: #242526; --mwp-header-background-color: var(--messenger-card-background); --mwp-header-button-color: var(--accent); --mwp-message-row-background: var(--messenger-card-background); --messenger-reply-background: #18191A; --overlay-alpha-80: rgba(0, 0, 0, 0.65); --overlay-on-media: rgba(0, 0, 0, 0.6); --nav-bar-background: #242526; --nav-bar-background-gradient: linear-gradient(to top, #242526, rgba(36,37,38,.9), rgba(36,37,38,.7), rgba(36,37,38,.4), rgba(36,37,38,0)); --nav-bar-background-gradient-wash: linear-gradient(to top, #18191A, rgba(24,25,26,.9), rgba(24,25,26,.7), rgba(24,25,26,.4), rgba(24,25,26,0)); --negative: hsl(350, 87%, 55%); --negative-background: hsl(350, 87%, 55%, 20%); --new-notification-background: #E7F3FF; --non-media-pressed: rgba(68, 73, 80, 0.15); --non-media-pressed-on-dark: rgba(255, 255, 255, 0.3); --notification-badge: #e41e3f; --placeholder-icon: #8A8D91; --placeholder-image: rgb(164, 167, 171); --placeholder-text: #8A8D91; --placeholder-text-on-media: rgba(255, 255, 255, 0.5); --popover-background: #3E4042; --positive: #31A24C; --positive-background: #1F3520; --press-overlay: rgba(255, 255, 255, 0.1); --primary-button-background: #0095F6; --primary-button-icon: #FFFFFF; --primary-button-pressed: #77A7FF; --primary-button-text: #FFFFFF; --primary-deemphasized-button-background: rgba(45, 136, 255, 0.2); --primary-deemphasized-button-pressed: rgba(24, 119, 242, 0.2); --primary-deemphasized-button-pressed-overlay: rgba(25, 110, 255, 0.15); --primary-deemphasized-button-text: #2D88FF; --primary-icon: #E4E6EB; --primary-text: #E4E6EB; --primary-text-on-media: white; --primary-web-focus-indicator: #D24294; --progress-ring-neutral-background: rgba(255, 255, 255, 0.2); --progress-ring-neutral-foreground: #ffffff; --progress-ring-on-media-background: rgba(255, 255, 255, 0.2); --progress-ring-on-media-foreground: #FFFFFF; --progress-ring-blue-background: rgba(45, 136, 255, 0.2); --progress-ring-blue-foreground: hsl(214, 100%, 59%); --progress-ring-disabled-background: rgba(122,125,130, 0.2); --progress-ring-disabled-foreground: #7A7D82; --rating-star-active: #FF9831; --scroll-thumb: rgba(255, 255, 255, 0.3); --scroll-shadow: 0 1px 2px rgba(0, 0, 0, 0.1), 0 -1px rgba(255, 255, 255, 0.05) inset; --secondary-button-background: rgba(255,255,255,.1); --secondary-button-background-floating: #4B4C4F; --secondary-button-background-on-dark: rgba(255, 255, 255, 0.4); --secondary-button-pressed: rgba(0, 0, 0, 0.05); --secondary-button-stroke: transparent; --secondary-button-text: #E4E6EB; --secondary-icon: #B0B3B8; --secondary-text: #B0B3B8; --secondary-text-on-media: rgba(255, 255, 255, 0.9); --section-header-text: #BCC0C4; --shadow-1: rgba(0, 0, 0, 0.1); --shadow-2: rgba(0, 0, 0, 0.2); --shadow-5: rgba(0, 0, 0, 0.5); --shadow-8: rgba(0, 0, 0, 0.8); --shadow-inset: rgba(255, 255, 255, 0.05); --shadow-elevated: 0 8px 20px 0 rgba(0, 0, 0, 0.2), 0 2px 4px 0 rgba(0, 0, 0, 0.1); --shadow-persistent: 0px 0px 12px rgba(28, 43, 51, 0.6); --shadow-primary: 0px 0px 12px rgba(28, 43, 51, 0.1); --surface-background: #242526; --switch-active: hsl(214, 100%, 59%); --text-highlight: rgba(24, 119, 242, 0.45); --input-background: #242526; --input-background-disabled: #18191A; --input-border-color: #3E4042; --input-border-color-hover: var(--placeholder-text); --input-label-color-highlighted: hsl(214, 100%, 59%); --text-input-outside-label: #FFFFFF; --toast-background: #242526; --toast-text: #FFFFFF; --toast-text-link: #4599FF; --toggle-active-background: rgb(45, 136, 255); --toggle-active-icon: #FFFFFF; --toggle-active-text: #FFFFFF; --toggle-button-active-background: #E6F2FF; --tooltip-background: rgba(11, 11, 11, 0.8); --tooltip-box-shadow: 0 2px 4px 0 var(--shadow-5); --wash: #3E4042; --web-wash: #18191A; --warning: hsl(40, 89%, 52%); --chat-bubble-padding-vertical: 8px; --chat-bubble-padding-horizontal: 12px; --chat-bubble-border-radius: 18px; --chat-text-blockquote-color-background-line: rgba(255, 255, 255, 0.19); --chat-text-blockquote-color-text-primary-media: rgba(255, 255, 255, 0.7); --chat-incoming-message-bubble-background-color: #303030; --chat-outgoing-message-bubble-background-color: var(--accent); --chat-replied-message-background-color: rgba(255, 255, 255, 0.12); --radio-border-color: var(--primary-icon); --radio-border-color-disabled: var(--disabled-button-background); --radio-border-color-selected: var(--accent); --radio-checked-icon-color: var(--accent); --radio-checked-icon-color-disabled: var(--disabled-button-background); --fb-logo-color: #2D88FF; --dialog-anchor-vertical-padding: 56px; --header-height: 0px; --global-panel-width: 0px; --global-panel-width-expanded: 0px; --alert-banner-corner-radius: 8px; --button-corner-radius: 4px; --button-corner-radius-medium: 10px; --button-corner-radius-large: 12px; --button-height-large: 40px; --button-height-medium: 36px; --button-padding-horizontal-large: 16px; --button-padding-horizontal-medium: 16px; --button-icon-padding-large: 16px; --button-icon-padding-medium: 16px; --button-inner-icon-spacing-large: 3px; --button-inner-icon-spacing-medium: 3px; --blueprint-button-height-medium: 40px; --blueprint-button-height-large: 48px; --card-corner-radius: 4px; --card-box-shadow: 0 12px 28px 0 var(--shadow-2), 0 2px 4px 0 var(--shadow-1); --card-padding-horizontal: 10px; --card-padding-vertical: 20px; --chip-corner-radius: 6px; --dialog-corner-radius: 8px; --glimmer-corner-radius: 8px; --image-corner-radius: 4px; --input-corner-radius: 6px; --input-border-width: 1px; --nav-list-cell-corner-radius: 8px; --list-cell-corner-radius: 8px; --list-cell-min-height: 52px; --list-cell-padding-vertical: 20px; --list-cell-padding-vertical-with-addon: 14px; --menu-item-base-margin-horizontal: 8px; --menu-item-base-padding-horizontal: 8px; --nav-list-cell-min-height: 0px; --nav-list-cell-padding-vertical: 16px; --nav-list-cell-padding-vertical-with-addon: 16px; --page-footer-padding-vertical: 16px; --section-header-addOnEnd-margin-horizontal: 8px; --section-header-addOnStart-margin-horizontal: 12px; --section-header-addOnEnd-button-padding-horizontal: 0px; --section-header-addOnEnd-button-padding-vertical: 0px; --section-header-padding-vertical: 16px; --section-header-subtitle-margin-vertical: 14px; --section-header-subtitle-with-addOnEnd-margin-vertical: 6px; --text-badge-corner-radius: 4px; --text-badge-padding-horizontal: 6px; --text-badge-padding-vertical: 6px; --text-input-multi-padding-between-text-scrollbar: 20px; --text-input-multi-padding-scrollbar: 16px; --text-input-caption-margin-top: 10px; --text-input-label-top: 22px; --text-input-min-height: 64px; --text-input-padding-vertical: 12px; --toast-addon-padding-horizontal: 6px; --toast-addon-padding-vertical: 6px; --toast-container-max-width: 100%; --toast-container-min-width: 288px; --toast-container-padding-horizontal: 10px; --toast-container-padding-vertical: 16px; --toast-corner-radius: 8px; --tooltip-corner-radius: 8px; --typeahead-list-outer-padding-vertical: 2px; --fds-animation-enter-exit-in: cubic-bezier(0.14, 1, 0.34, 1); --fds-animation-enter-exit-out: cubic-bezier(0.45, 0.1, 0.2, 1); --fds-animation-swap-shuffle-in: cubic-bezier(0.14, 1, 0.34, 1); --fds-animation-swap-shuffle-out: cubic-bezier(0.45, 0.1, 0.2, 1); --fds-animation-move-in: cubic-bezier(0.17, 0.17, 0, 1); --fds-animation-move-out: cubic-bezier(0.17, 0.17, 0, 1); --fds-animation-expand-collapse-in: cubic-bezier(0.17, 0.17, 0, 1); --fds-animation-expand-collapse-out: cubic-bezier(0.17, 0.17, 0, 1); --fds-animation-passive-move-in: cubic-bezier(0.5, 0, 0.1, 1); --fds-animation-passive-move-out: cubic-bezier(0.5, 0, 0.1, 1); --fds-animation-quick-move-in: cubic-bezier(0.1, 0.9, 0.2, 1); --fds-animation-quick-move-out: cubic-bezier(0.1, 0.9, 0.2, 1); --fds-animation-fade-in: cubic-bezier(0, 0, 1, 1); --fds-animation-fade-out: cubic-bezier(0, 0, 1, 1); --fds-duration-extra-extra-short-in: 100ms; --fds-duration-extra-extra-short-out: 100ms; --fds-duration-extra-short-in: 200ms; --fds-duration-extra-short-out: 150ms; --fds-duration-short-in: 280ms; --fds-duration-short-out: 200ms; --fds-duration-medium-in: 400ms; --fds-duration-medium-out: 350ms; --fds-duration-long-in: 500ms; --fds-duration-long-out: 350ms; --fds-duration-extra-long-in: 1000ms; --fds-duration-extra-long-out: 1000ms; --fds-duration-none: 0ms; --fds-fast: 200ms; --fds-slow: 400ms; --font-family-apple: system-ui, -apple-system, BlinkMacSystemFont, '.SFNSText-Regular', sans-serif; --font-family-code: ui-monospace, Menlo, Consolas, Monaco, monospace; --font-family-default: Helvetica, Arial, sans-serif; --font-family-segoe: Segoe UI Historic, Segoe UI, Helvetica, Arial, sans-serif; --body-font-family: Placeholder Font; --body-font-size: 0.9375rem; --body-font-weight: 400; --body-line-height: 1.3333; --body-emphasized-font-family: Placeholder Font; --body-emphasized-font-size: 0.9375rem; --body-emphasized-font-weight: 600; --body-emphasized-line-height: 1.3333; --headline1-font-family: Optimistic Display Bold, system-ui, sans-serif; --headline1-font-size: 1.75rem; --headline1-font-weight: 700; --headline1-line-height: 1.2143; --headline2-font-family: Optimistic Display Bold, system-ui, sans-serif; --headline2-font-size: 1.5rem; --headline2-font-weight: 700; --headline2-line-height: 1.25; --headline3-font-family: Optimistic Display Bold, system-ui, sans-serif; --headline3-font-size: 1.0625rem; --headline3-font-weight: 700; --headline3-line-height: 1.2941; --meta-font-family: Placeholder Font; --meta-font-size: 0.8125rem; --meta-font-weight: 400; --meta-line-height: 1.3846; --meta-emphasized-font-family: Placeholder Font; --meta-emphasized-font-size: 0.8125rem; --meta-emphasized-font-weight: 600; --meta-emphasized-line-height: 1.3846; --primary-label-font-family: Optimistic Display Medium, system-ui, sans-serif; --primary-label-font-size: 1.0625rem; --primary-label-font-weight: 500; --primary-label-line-height: 1.2941; --secondary-label-font-family: Placeholder Font; --secondary-label-font-size: 0.9375rem; --secondary-label-font-weight: 500; --secondary-label-line-height: 1.3333; --tertiary-label-font-family: Placeholder Font; --tertiary-label-font-size: 0.6875rem; --tertiary-label-font-weight: 500; --tertiary-label-line-height: 1.4545; --text-input-field-font-family: Placeholder Font; --text-input-field-font-size: 1rem; --text-input-field-font-weight: 500; --text-input-field-line-height: 1.2941; --text-input-label-font-family: Placeholder Font; --text-input-label-font-size: 17px; --text-input-label-font-size-scale-multiplier: 0.75; --text-input-label-font-weight: 400; --text-input-label-line-height: 1.2941; --dialog-size-medium-max-width: 700px; --dialog-size-medium-width: 100%; --dialog-size-small-max-width: 548px; --dialog-size-small-width: 100%; --focus-ring-outline-link: 2px auto var(--focus-ring-blue); --focus-ring-shadow-default: 0 0 0 2px var(--always-white), 0 0 0 4px var(--focus-ring-blue); --focus-ring-shadow-inset: 0 0 0 2px var(--focus-ring-blue) inset, 0 0 0 4px var(--always-white) inset; --glimmer-animation-direction: alternate; --glimmer-animation-duration: 1000ms; --glimmer-animation-timing-function: steps(10, end); --glimmer-opacity-min: 0.25; --glimmer-opacity-max: 1; --radio-checked-icon-size-large: 12px; --radio-checked-icon-size-medium: 12px; --radio-border-width: 2px; --radio-size-large: 24px; --radio-size-medium: 20px; --blue-primary: rgb(0,136,244); --blue-secondary: rgb(235,245,255); --blue-tertiary: rgb(4,59,114); --chartreuse-primary: rgb(106,147,22); --chartreuse-secondary: rgb(226,255,152); --chartreuse-tertiary: rgb(50,65,19); --cyan-primary: rgb(0,142,213); --cyan-secondary: rgb(231,245,255); --cyan-tertiary: rgb(15,63,93); --dataviz-primary-2: rgb(134,218,255); --dataviz-primary-3: rgb(73,156,255); --dataviz-secondary-1: rgb(129,77,231); --dataviz-secondary-2: rgb(168,124,255); --dataviz-secondary-3: rgb(219,26,139); --dataviz-supplementary-1: rgb(255,122,105); --dataviz-supplementary-2: rgb(241,168,23); --dataviz-supplementary-3: rgb(49,162,76); --dataviz-supplementary-4: rgb(228,230,235); --fuschia-primary: rgb(250,45,138); --fuschia-secondary: rgb(255,241,246); --fuschia-tertiary: rgb(118,14,62); --green-primary: rgb(43,154,53); --green-secondary: rgb(227,250,224); --green-tertiary: rgb(26,68,27); --magenta-primary: rgb(215,77,204); --magenta-secondary: rgb(255,239,254); --magenta-tertiary: rgb(96,36,91); --orange-primary: rgb(208,108,20); --orange-secondary: rgb(255,241,239); --orange-tertiary: rgb(94,49,14); --purple-primary: rgb(125,116,255); --purple-secondary: rgb(245,241,255); --purple-tertiary: rgb(55,50,121); --red-primary: rgb(251,60,68); --red-secondary: rgb(255,241,239); --red-tertiary: rgb(118,22,27); --teal-primary: rgb(0,152,124); --teal-secondary: rgb(227,247,241); --teal-tertiary: rgb(10,68,56); --yellow-primary: rgb(161,132,0); --yellow-secondary: rgb(255,246,161); --yellow-tertiary: rgb(72,59,12); --base-unit: 4px; --blue-0: 245, 251, 255; --blue-1: 224, 241, 255; --blue-2: 179, 219, 255; --blue-3: 112, 188, 255; --blue-4: 71, 175, 255; --blue-5: 0, 149, 246; --blue-6: 0, 116, 204; --blue-7: 0, 87, 163; --blue-8: 0, 55, 107; --blue-9: 0, 41, 82; --breakpoint-medium-width: 1536px; --breakpoint-small-width: 1024px; --challenge-width: 460px; --creation-header-height: 43px; --creation-min-padding-x: 32px; --creation-modal-max-height: 898px; --creation-modal-min-height: 391px; --creation-padding-x: 64px; --creation-padding-y: 112px; --creation-settings-width: 340px; --cyan-5: 39, 196, 245; --desktop-grid-item-margin: 28px; --desktop-grid-item-margin-slim: 4px; --desktop-in-feed-story-item-height: 208px; --desktop-in-feed-story-item-width: 116px; --desktop-nav-height: 60px; --desktop-skinny-nav-height: 60px; --desktop-story-tray-bottom-margin: 48px; --desktop-story-tray-bottom-margin-denser: 24px; --direct-attachment-image-grid-item-size: 78px; --direct-attachment-story-height: 150px; --direct-attachment-story-large-height: 256px; --direct-attachment-story-large-width: 164px; --direct-attachment-story-width: 84px; --direct-message-max-width: 236px; --fb-signup-page-profile-pic-size: 88px; --feed-sidebar-padding: 32px; --feed-sidebar-width: 319px; --feed-width: 470px; --feed-width-wide-story: 630px; --font-family-system: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Helvetica, Arial, sans-serif; --font-family-system-prism: &quot;Instagram Sans UI&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Helvetica, Arial, sans-serif; --font-weight-system-bold: 700; --font-weight-system-extra-bold: 800; --font-weight-system-extra-light: 200; --font-weight-system-light: 300; --font-weight-system-medium: 500; --font-weight-system-regular: 400; --font-weight-system-semibold: 600; --footer-width-wide: 1150px; --gradient-lavender: 211, 0, 197; --gradient-orange: 255, 122, 0; --gradient-pink: 255, 1, 105; --gradient-purple: 118, 56, 250; --gradient-red: 255, 48, 64; --gradient-yellow: 255, 214, 0; --green-4: 120, 222, 69; --green-5: 88, 195, 34; --green-6: 55, 166, 0; --grey-0: 245, 245, 245; --grey-1: 239, 239, 239; --grey-2: 219, 219, 219; --grey-3: 199, 199, 199; --grey-4: 168, 168, 168; --grey-5: 142, 142, 142; --grey-6: 115, 115, 115; --grey-7: 85, 85, 85; --grey-8: 54, 54, 54; --grey-9: 38, 38, 38; --grey-10: 26, 26, 26; --grey-0-prism: 248, 249, 249; --grey-1-prism: 243, 245, 247; --grey-2-prism: 233, 237, 240; --grey-3-prism: 219, 223, 228; --grey-4-prism: 162, 170, 180; --grey-5-prism: 131, 137, 147; --grey-6-prism: 111, 118, 128; --grey-7-prism: 94, 100, 109; --grey-8-prism: 50, 53, 57; --grey-9-prism: 41, 41, 46; --grey-10-prism: 33, 35, 38; --ig-badge: 255, 48, 64; --ig-close-friends-refreshed: 28, 209, 79; --ig-disabled-action-text: 169, 219, 255; --ig-error-or-destructive: 237, 73, 86; --ig-facebook-blue: 53, 121, 234; --ig-live-badge: 255, 1, 105; --ig-primary-button: 0, 149, 246; --ig-primary-button-hover: 24, 119, 242; --ig-secondary-icon: 142, 142, 142; --ig-stroke-on-media: 255, 255, 255; --ig-tertiary-button-background: 255, 255, 255; --ig-tertiary-button-border: 219, 219, 219; --ig-tertiary-button-hover: 245, 245, 245; --ig-tertiary-button-text: 38, 38, 38; --ig-subscribers-only: 118, 56, 250; --ig-success: 88, 195, 34; --ig-text-on-color: 255, 255, 255; --ig-text-on-media: 255, 255, 255; --in-feed-story-item-height: 240px; --in-feed-story-item-width: 135px; --in-feed-story-item-padding: 12px; --input-border-radius: 6px; --large-layout-min: 1500px; --live-video-border-radius: 4px; --media-content-card-width: 350px; --media-content-card-width-small: 300px; --media-info: 335px; --medium-layout-max: 1499px; --medium-layout-min: 1080px; --medium-screen-max: 875px; --medium-screen-min: 736px; --mobile-grid-item-margin: 2px; --mobile-nav-height: 45px; --modal-backdrop-dark: rgba(0, 0, 0, 0.85); --modal-backdrop-default: rgba(0, 0, 0, 0.65); --modal-border-radius: 12px; --modal-padding: 16px; --modal-z-index: 100; --nav-narrow-width: 72px; --nav-medium-width: 244px; --nav-wide-width: 335px; --nav-bottom-screen-max: 767px; --nav-narrow-screen-min: 768px; --nav-medium-screen-min: 1264px; --nav-wide-screen-min: 1920px; --orange-5: 253, 141, 50; --photo: 600px; --pink-5: 209, 8, 105; --purple-5: 163, 7, 186; --red-4: 255, 104, 116; --red-5: 237, 73, 86; --red-6: 198, 35, 48; --red-7: 167, 3, 17; --reels-large-screen-min: 1366px; --refinement-section-height: 50px; --revamp-nav-bottom-toolbar-height: 50px; --revamp-feed-card-max-height: 835px; --revamp-feed-card-min-height: 615px; --revamp-feed-card-media-min-width: 390px; --revamp-feed-card-dense-padding: 16px; --revamp-feed-item-spacing: 20px; --revamp-feed-horizontal-padding-small-screen: 24px; --revamp-feed-horizontal-padding-large-screen: 32px; --revamp-feed-vertical-padding: 32px; --right-rail-width: 300px; --scrollable-content-header-height-large: 56px; --scrollable-content-header-height-med: 49px; --scrollable-content-header-height: 44px; --search-box-height: 40px; --search-modal-height-expanded: 450px; --search-modal-height: 362px; --search-modal-top-offset: 12px; --search-result-height: 50px; --search-result-inline-top-offset: 60px; --search-result-list-width: 375px; --site-width-narrow: 600px; --site-width-wide: 935px; --small-layout-max: 1079px; --small-layout-min: 800px; --small-screen-max: 735px; --small-screen-min: 414px; --story-progressbar-update-tick: 0.1s; --story-swap-animation-duration: 350ms; --system-10-font-size: 10px; --system-10-line-height: 12px; --system-11-font-size: 11px; --system-11-line-height: 13px; --system-12-font-size: 12px; --system-12-line-height: 16px; --system-14-font-size: 14px; --system-14-line-height: 18px; --system-16-font-size: 16px; --system-16-line-height: 20px; --system-18-font-size: 18px; --system-18-line-height: 24px; --system-20-font-size: 20px; --system-20-line-height: 25px; --system-22-font-size: 22px; --system-22-line-height: 26px; --system-24-font-size: 24px; --system-24-line-height: 27px; --system-26-font-size: 26px; --system-26-line-height: 28px; --system-28-font-size: 28px; --system-28-line-height: 32px; --system-30-font-size: 30px; --system-30-line-height: 36px; --system-32-font-size: 32px; --system-32-line-height: 40px; --web-always-black: 0, 0, 0; --web-always-white: 255, 255, 255; --web-overlay-on-media: 38, 38, 38; --web-prism-black: 15, 20, 25; --web-secondary-action: 224, 241, 255; --yellow-5: 253, 203, 92; --barcelona-logo: 255, 255, 255; --challenge-link: 219, 219, 219; --ig-banner-background: 38, 38, 38; --ig-elevated-background: 38, 38, 38; --ig-elevated-highlight-background: 54, 54, 54; --ig-elevated-separator: 54, 54, 54; --ig-focus-stroke: 85, 85, 85; --ig-highlight-background: 38, 38, 38; --ig-hover-overlay: 255, 255, 255, 0.1; --ig-link: 224, 241, 255; --ig-primary-background: 0, 0, 0; --ig-primary-icon: 245, 245, 245; --ig-primary-text: 245, 245, 245; --ig-secondary-background: 26, 26, 26; --ig-secondary-button: 245, 245, 245; --ig-secondary-button-background: 85, 85, 85, 0.7; --ig-secondary-button-hover: 54, 54, 54; --ig-secondary-text: 168, 168, 168; --ig-separator: 38, 38, 38; --ig-stroke: 54, 54, 54; --ig-temporary-highlight: 0, 149, 246; --ig-tertiary-icon: 115, 115, 115; --ig-tertiary-text: 115, 115, 115; --post-separator: 38, 38, 38; --tos-box-shadow: 255, 255, 255; --ig-primary-link-pressed-prism-ab: 233, 237, 240; --ig-primary-link-pressed-prism-c: 0, 116, 204; --ig-primary-link-prism-ab: 248, 249, 249; --ig-primary-link-prism-c: 0, 149, 246; --ig-primary-button-text-pressed-prism-ab: 41, 41, 46; --ig-primary-button-text-pressed-prism-c: 248, 249, 249; --ig-primary-button-text-prism-ab: 15, 20, 25; --ig-primary-button-text-prism-c: 255, 255, 255; --ig-primary-button-text-disabled-prism-ab: 50, 53, 57; --ig-primary-text-disabled-prism-c: 162, 170, 180; --ig-primary-link-disabled-prism-ab: 94, 100, 109; --ig-primary-link-disabled-prism-c: 0, 55, 107; --ig-secondary-link-prism-ab: 179, 219, 255; --ig-secondary-link-prism-c: 248, 249, 249; --ig-secondary-link-disabled-prism-ab: 0, 55, 107; --ig-secondary-link-disabled-prism-c: 94, 100, 109; --ig-secondary-button-text-pressed-prism-ab: 233, 237, 240; --ig-secondary-button-text-pressed-prism-c: 233, 237, 240; --ig-secondary-button-text-prism: 248, 249, 249; --ig-secondary-button-text-disabled-prism-ab: 94, 100, 109; --ig-primary-button-prism-ab: 248, 249, 249; --ig-primary-button-prism-c: 0, 149, 246; --ig-primary-button-pressed-prism-ab: 233, 237, 240; --ig-primary-button-pressed-prism-c: 0, 116, 204; --ig-primary-button-disabled-prism-ab: 94, 100, 109; --ig-primary-button-disabled-prism-c: 0, 55, 107; --ig-secondary-button-prism-ab: 15, 20, 25; --ig-secondary-button-prism-c: 41, 41, 46; --ig-toggle-background-on-prism: 248, 249, 249; --ig-toggle-background-off-prism: 50, 53, 57; --ig-toggle-background-disabled-on-prism: 111, 118, 128; --ig-toggle-background-disabled-off-prism: 41, 41, 46; --ig-toggle-outline-prism: 219, 223, 228; --ig-toggle-outline-disabled-prism: 94, 100, 109; --ig-stroke-prism: 15, 20, 25; --ig-stroke-disabled-on-prism: 50, 53, 57; --ig-stroke-disabled-off-prism: 33, 35, 38;">...</div>
  (Session info: chrome=114.0.5735.45)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x008E6E73+48323]
	(No symbol) [0x00879661]
	(No symbol) [0x00785308]
	(No symbol) [0x007B5202]
	(No symbol) [0x007B3D38]
	(No symbol) [0x007B253B]
	(No symbol) [0x007B193E]
	(No symbol) [0x007AA0FC]
	(No symbol) [0x007CA8DC]
	(No symbol) [0x007A9BD6]
	(No symbol) [0x007CAC34]
	(No symbol) [0x007DCAC2]
	(No symbol) [0x007CA6D6]
	(No symbol) [0x007A847C]
	(No symbol) [0x007A957D]
	GetHandleVerifier [0x00B4FD5D+2575277]
	GetHandleVerifier [0x00B8F86E+2836158]
	GetHandleVerifier [0x00B896DC+2811180]
	GetHandleVerifier [0x009741B0+626688]
	(No symbol) [0x0088314C]
	(No symbol) [0x0087F4B8]
	(No symbol) [0x0087F59B]
	(No symbol) [0x008721B7]
	BaseThreadInitThunk [0x75AE7BA9+25]
	RtlInitializeExceptionChain [0x7745BD2B+107]
	RtlClearBits [0x7745BCAF+191]

==>> Traceback:
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\core\HomeController.py", line 87, in run
    self.uploadInstagram(browser)
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\core\HomeController.py", line 1155, in uploadInstagram
    self.__instagram(browser, indexVideo)
  File "c:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\core\HomeController.py", line 1068, in __instagram
    create.click()
  File "C:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\.venv\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 93, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\.venv\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 394, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\hokag\Documents\GitHub\Folinas-Social-Tools\.venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)

